# -*- coding: utf-8 -*-
"""Admin dashboard findings."""
APP = 'Admin dashboard'
KEY = 'admin'
FINDINGS = [
 dict(id='A-H1', sev='HIGH', status='closed', cat='Security', critical=True,
      title='PUT /admin/rate-card was completely unauthenticated in production',
      loc='seirs-backend/src/pricing/pricing.controller.ts:208-209',
      detail='@Controller() carries no class-level guards. Lines 156 and 171 both stacked @UseGuards(JwtAuthGuard, SuperAdminGuard) onto the SAME method (syncFuel) because a JSDoc block sat between the first decorator and its handler; publishRateCard got nothing. The only APP_GUARD is HttpThrottlerGuard, so there is no global JWT guard to fall back on. Anyone on the internet could publish a new rate card and reprice every delivery and ride on the platform.',
      fix='Verified exploitable against production first (an unauthenticated PUT reached the handler body and returned 400 changeReason required rather than 401), then guarded, redeployed, and re-verified returning 401. Every controller swept for the same decorator-orphaning shape: none remaining.'),
 dict(id='A-H2', sev='HIGH', status='open', cat='Permissions',
      title='Role changes in Staff Management do not change any backend permission',
      loc='roles.service.ts:128, super-admin.guard.ts:29, admin.service.ts:88, admins/page.tsx:437',
      detail='assignToUser writes only roleId while every backend gate reads adminRole. Demoting a super admin to a read-only custom role leaves them able to publish pricing, seed demo credentials, offboard colleagues and hard-delete accounts. Promoting someone to Super Admin grants them none of it. A custom-role admin has adminRole null, so every PII reveal, bank-change approval and NDPR export 403s with "Your role: none". adminApi.admins.updateRole, which does set adminRole, is dead code.',
      fix='Have assignToUser also set adminRole to role.slug for system roles, or teach the guards to resolve via roleId.'),
 dict(id='A-H3', sev='HIGH', status='open', cat='Security',
      title='Two-factor auth does not exist, but the login page has a TOTP step',
      loc='src/lib/api.ts:60-64, login/page.tsx:32',
      detail='Posts /auth/admin-totp-verify; auth.controller.ts has no such route. requiresTOTP and tempToken appear nowhere in the backend, so the branch is unreachable dead code that would 404 if reached. The backend DOES have totp/setup and totp/confirm, but no dashboard page calls them, so 2FA can never be enrolled either. Anyone believing admin 2FA is on is wrong.',
      fix='Build the endpoint and enrolment UI, or delete the TOTP step.'),
 dict(id='A-H4', sev='HIGH', status='open', cat='Dead controls',
      title='"Send Password Reset Email" and "Reactivate Account" hit routes that do not exist',
      loc='src/lib/api.ts:141-143, admins/page.tsx:456,513',
      detail='The only admins/:id/* routes are role, totp/setup, totp/confirm, offboard and footprint. Consequence: an admin who is offboarded can NEVER be brought back, because the Reactivate button always errors and there is no other path. deactivate is dead code with no caller.',
      fix='Add the two routes (reactivate is a one-line isActive true plus audit); point reset-password at the working POST /auth/forgot-password, which already branches the link to the admin web URL.'),
 dict(id='A-H5', sev='HIGH', status='open', cat='Dead controls',
      title='Driver-assignment search returns an unfiltered list',
      loc='deliveries/page.tsx:331, admin.controller.ts:246',
      detail='getDrivers has no search parameter. The dispatcher types "Chinedu", the modal returns the same arbitrary first 20 approved drivers, and the empty state "No approved drivers match that search" can never fire. On a platform with more than 20 approved drivers the manual-dispatch picker is a lottery.',
      fix='Accept search on GET /admin/drivers and ILIKE against user.name, user.phone, vehiclePlate.'),
 dict(id='A-H6', sev='HIGH', status='open', cat='Dead controls',
      title='The push composer one-person search can send to the wrong customer',
      loc='notify/page.tsx:52, admin.controller.ts:133',
      detail='getUsers drops search, so the composer shows the first 8 users on page 1 regardless of what was typed and the operator picks one believing it matched. This sends a real push notification to a real stranger.',
      fix='Add search to GET /admin/users, or switch the composer to adminApi.search(q), the endpoint actually built for this.'),
 dict(id='A-H7', sev='HIGH', status='open', cat='Dead controls',
      title='The fraud page "Action (Ban)" does not ban anyone',
      loc='fraud/page.tsx:97-102, fraud.service.ts:102-105',
      detail='resolveFlag only updates the flag row status. The user stays fully active. A risk officer clears the queue believing fraudsters are locked out. There is also no confirm dialog and no link from a flag to the account.',
      fix='Rename to "Mark Actioned" and add a separate explicit ban behind a confirm, plus a link to /users/{id}.'),
 dict(id='A-H8', sev='HIGH', status='open', cat='Wrong data',
      title='/dev-usage shows the logged-in admin own key stats as "Platform API Stats"',
      loc='dev-usage/page.tsx:17, dev-platform.service.ts:335',
      detail='getUsageStats filters by ownerUserId, which is the ADMIN id. Admins hold no developer keys, so Total Keys / Active Keys / Calls Today are permanently 0 under a heading saying "Aggregate Developer Platform usage". /dev-accounts correctly uses listAllKeys().',
      fix='Point at listAccounts() and aggregate, or add an admin-scoped usage endpoint.'),
 dict(id='A-H9', sev='HIGH', status='open', cat='Wrong data',
      title='Last-Order Compliance reads a field the API never returns, and states a rule nothing enforces',
      loc='last-order-compliance/page.tsx:45,57, admin.service.ts:1340-1352',
      detail='Filters on d.lastOrderActiveAt, which driverComplianceStats never returns (the entity column is lastOrderEnabledAt). So "Currently Winding Down" is permanently 0 and the badge never renders: the page whole named purpose is inert. Line 57 also states "Drivers below 80% cannot enable the wind-down mode" while drivers.service.ts says the gate is informational only and performs no check.',
      fix='Return lastOrderMode and lastOrderEnabledAt, and either enforce the gate or change the copy.'),
 dict(id='A-H10', sev='HIGH', status='open', cat='Dead controls',
      title='The push composer Schedule control silently sends immediately',
      loc='notify/page.tsx:281-298,71-113,317',
      detail='Renders a Schedule button and datetime picker, requires a datetime, and the submit reads "Schedule broadcast", but send() never passes scheduleAt anywhere: the broadcast fires now. The code comment admits it and claims the toast surfaces it, but that note is only set on the one_user branch. An ops person schedules "Service resumes at 6am" and every customer phone buzzes at 11pm.',
      fix='Disable Schedule with an explicit "not available yet", or set the note on the broadcast path.'),
 dict(id='A-H11', sev='HIGH', status='open', cat='Dead controls',
      title='The Featured Promotion widget cannot save on a fresh database',
      loc='settings/page.tsx:237, admin.service.ts:2477-2479,2449-2456',
      detail='updatePlatformConfig throws NotFoundException for an unknown key, and featured_promotion is not in DEFAULT_CONFIG. Nothing ever inserts the row, so "Publish Promotion" returns "Unknown config key: featured_promotion". The hero card on the customer Rewards tab can never be set from the dashboard.',
      fix='Add featured_promotion to DEFAULT_CONFIG, or make the update upsert for an allow-list.'),
 dict(id='A-H12', sev='HIGH', status='open', cat='Money',
      title='Every percentage promotion created from the dashboard is uncapped',
      loc='promotions/page.tsx:203-227,150-158',
      detail='CreatePromoModal never sends maxDiscountKobo or minSubtotalKobo and has no input for either. The entity own comment is explicit: "Optional cap for % discounts so a 50% promo on a N40k delivery does not haemorrhage margin. Null = no cap." The list table does not display the cap either, so an admin cannot even see that existing promos are uncapped. This is the every-perk-needs-a-cap rule failing on the one surface that mints discounts.',
      fix='Add Max discount and Min subtotal fields, convert to kobo, default the max non-null for percent, and add a Cap column.'),
 dict(id='A-H13', sev='HIGH', status='open', cat='Dead controls',
      title='There is no way to reject a driver KYC application anywhere in the dashboard',
      loc='src/lib/api.ts:164-165 (zero callers), drivers/page.tsx:136-145, drivers/[id]/page.tsx:210-227',
      detail='adminApi.rejectDriver exists and is never called. The list offers Approve and Suspend; the detail offers Approve KYC / Suspend / Reinstate. A pending applicant with a forged licence can only be approved or left in the queue forever.',
      fix='Add a Reject button with a required reason, wired to the existing endpoint.'),
 dict(id='A-H14', sev='HIGH', status='open', cat='Money',
      title='Money renders as raw Postgres decimal strings on four surfaces',
      loc='deliveries/page.tsx:206, users/[id]/page.tsx:402, drivers/[id]/page.tsx:523, page.tsx:506',
      detail='price and driverEarnings are decimal columns with no numeric transformer, so node-postgres returns "1500.00" and String.toLocaleString leaves it unchanged: N1500.00. Fractional naira breaks the house standard, and the missing separator makes N1500 and N15000 hard to tell apart in a scan. The delivery DETAIL page rounds correctly, so the same order shows two different numbers on two pages.',
      fix='Use the existing naira() helper everywhere, or add a numeric transformer on the columns.'),
 dict(id='A-H15', sev='HIGH', status='open', cat='Security',
      title='Stored XSS in the ops-map info windows',
      loc='ops-map/page.tsx:209,254,278,355',
      detail='Interpolated strings go to infoWindow.setContent, which Google Maps parses as HTML. d.name, s.storeName, s.storeAddress and a.user.name are all user-supplied, and label at 355 comes from the ?label= query param (reflected). A driver who sets their name to an img onerror payload exfiltrates the admin session token from localStorage the moment ops clicks their pin.',
      fix='Build the info window with createElement and textContent, or HTML-escape every interpolated value.'),
 dict(id='A-H16', sev='HIGH', status='open', cat='Permissions',
      title='Fee Catalogue Save always 403s for the roles the nav grants',
      loc='fees.controller.ts:59-60, rbac.ts:38,40,128, fees/page.tsx:320-327',
      detail='The PATCH is super-admin only, but the nav grants fees to ops_manager and finance_officer and puts Fee Catalogue in their sidebar. Those admins can open every fee, edit it, hit an always-enabled Save and get an alert. The same applies to the FuelDriftBanner "Apply pump prices and publish", which renders on the dashboard home for those roles but calls a super-admin-only route.',
      fix='Gate both buttons on isSuperAdminFromUser with a read-only note, matching what /website already does.'),
 dict(id='A-H17', sev='HIGH', status='open', cat='Permissions',
      title='NDPR hard-delete is offered to roles the API will refuse',
      loc='users/[id]/page.tsx:224-232,33 and drivers/[id]/page.tsx:239-243',
      detail='Both render "NDPR hard-delete" and "Export NDPR data" unconditionally, while the service gates them to super_admin plus support_agent (delete) or finance_officer (export). /users and /drivers are granted to ops_manager and driver_compliance, so those roles get a fully enabled irreversible-purge button that 403s only AFTER they have typed the reason and confirmed the name. Tellingly, users/[id] already computes superAdmin and never uses it: the guard was written and not wired. /recycle-bin "Delete forever" has the same problem.',
      fix='Wrap the destructive buttons in the role check that is already computed.'),
 dict(id='A-H18', sev='HIGH', status='open', cat='Permissions',
      title='The middleware permission map is a stale copy missing about 15 routes',
      loc='src/middleware.ts:11-48',
      detail='PATH_PERMISSIONS has 25 entries; NAV_SECTIONS has 39 pages. Ungated: /roles, /fees, /identity, /recycle-bin, /website, /notify, /email-templates, /health, /disputes, /interstate, /last-order-compliance, /service-catalog, /partner-applications, /dev-accounts, /dev-usage, /dev-docs, /sos. A media_content admin can navigate straight to Role Management. ROLE_PERMS is a second divergent copy of PERMISSIONS. And because decodeJwtRole reads adminRole ?? role from a JWT that carries no roleSlug, any custom-role admin decodes as "admin", fails isKnownGranularRole, and gets NO middleware gating at all.',
      fix='Derive PATH_PERMISSIONS from NAV_SECTIONS, import PERMISSIONS instead of copying it, and put roleSlug and permissions in the JWT.'),
 dict(id='A-M1', sev='MEDIUM', status='open', cat='Wrong data',
      title='Analytics revenue chart X-axis is blank',
      loc='analytics/page.tsx:109-110,116',
      detail='dataKey "day" with a date tickFormatter, but getRevenueByDay returns { date, revenue, count } where date is already a formatted string like "5 Aug". So r.day is undefined, the axis renders nothing, and the tooltip produces "Invalid Date". The dashboard home gets it right.',
      fix='dataKey="date" and drop both formatters.'),
 dict(id='A-M2', sev='MEDIUM', status='open', cat='Wrong data',
      title='The SOS desk can never link to the booking',
      loc='sos/page.tsx:128-135, sos.service.ts:133-137',
      detail='listActive does a find with no relations and SosAlert.delivery is not eager, so a.delivery is always undefined and "Open their booking" never appears. user IS eager so name and phone work. This is the one screen whose stated job is the first minute of an emergency.',
      fix="relations: ['delivery']."),
 dict(id='A-M3', sev='MEDIUM', status='open', cat='Dead controls',
      title='Chat re-open has no early close',
      loc='src/lib/api.ts:627-631, support/page.tsx:438-461',
      detail='chatReopen.close is defined against a live backend route and nothing calls it, while the api.ts comment promises "and close it early". Support can open a 24h PII window and cannot shut it.',
      fix='Add a Close-chat button beside Re-open.'),
 dict(id='A-M4', sev='MEDIUM', status='open', cat='Dead controls',
      title='Published CMS items cannot be edited',
      loc='cms/page.tsx', detail='cms.update is defined with no caller; the page offers create, approve, publish and delete only. A typo in a live in-app banner requires delete and recreate, losing its id.',
      fix='Wire an edit action.'),
 dict(id='A-M5', sev='MEDIUM', status='open', cat='Dead controls',
      title='CMS banners can never carry an image',
      loc='cms/page.tsx:19,238,137-175',
      detail='imageUrl is typed and a thumbnail is rendered, but the create modal has only Type, Title and Body. adminApi.upload.image is used on /website but not here. Given the app-must-look-alive rule, an image-less banner system is a real gap.',
      fix='Add the uploader to the modal.'),
 dict(id='A-M6', sev='MEDIUM', status='open', cat='Wrong data',
      title='Revoked and expired identity verifications become unreachable',
      loc='identity/page.tsx:163',
      detail='Tabs render only submitted, approved, rejected and withdrawn, though the status type, the styles and the API all support revoked and expired. An admin revokes a verification and the record disappears from the UI.',
      fix='Add the two tabs.'),
 dict(id='A-M7', sev='MEDIUM', status='open', cat='Admin identity',
      title='/partner-applications shows a truncated UUID instead of the applicant',
      loc='partner-applications/page.tsx:124, partner-store.service.ts:1899-1904',
      detail='Renders the first 8 characters of userId because the query loads bare store rows with no user relation. An admin grants partner capability without ever seeing the owner name, email or SEIRS ID, and cannot click through. Against the admin-always-sees-identity rule.',
      fix="relations: ['user'] and render name/email/phone plus a link."),
 dict(id='A-M8', sev='MEDIUM', status='open', cat='Admin identity',
      title='/dev-accounts identifies developer accounts only by raw UUID',
      loc='dev-accounts/page.tsx:140, dev-platform.service.ts:86-88',
      detail='listAllKeys has no owner join, so suspending a developer account means suspending a UUID.', fix='Join the owner.'),
 dict(id='A-M9', sev='MEDIUM', status='open', cat='Wrong data',
      title='Referral "Credited" does not mean a bonus was paid',
      loc='admin.service.ts:2431, referrals/page.tsx:67',
      detail='status is derived purely from finding a user whose accountId matches the code. The actual award runs through the 7-gate awardReferralBonusIfEligible on DELIVERED. The founder reads a payout rate that is really a code-resolution rate.',
      fix='Derive the status from the actual award rows.'),
 dict(id='A-M10', sev='MEDIUM', status='open', cat='Audit trail',
      title='Rate-card history always says the change was made by "admin"',
      loc='pricing/page.tsx:117,230, pricing.controller.ts:227',
      detail="activatedBy is hardcoded to the literal string 'admin' client-side and the controller spreads the body verbatim, so the History By column is 'admin' for every version. Pricing changes are unattributable. syncFuel does it correctly with the real name.",
      fix='Drop the field client-side and set it from @CurrentUser().'),
 dict(id='A-M11', sev='MEDIUM', status='open', cat='Wrong data',
      title='The Health page "Auth" check probes the same endpoint as "Backend API"',
      loc='health/page.tsx:40-41,7-8',
      detail='Both rows call adminApi.stats(): two green rows, one probe. The file comment also claims it pings each external dependency; nothing touches Flutterwave, Google Maps, R2 or email.',
      fix='Point the auth row at GET /auth/me and add real dependency probes or correct the comment.'),
 dict(id='A-M12', sev='MEDIUM', status='open', cat='Permissions',
      title='Audit Log is gated by the legacy role field only',
      loc='audit-log/page.tsx:61, cms/page.tsx:58-59, rbac.ts:41',
      detail='Uses isSuperAdmin(getAdminRole()) which reads user.adminRole, so a super admin on a dynamic role sees "Access Restricted". Every other page uses isSuperAdminFromUser, which handles both. Conversely the nav grants /audit-log to driver_compliance, who always hits the block screen: a nav entry to a wall.',
      fix='Use isSuperAdminFromUser and fix the nav grant.'),
 dict(id='A-M13', sev='MEDIUM', status='open', cat='Wrong data',
      title='Audit Log "Previous" duplicates rows',
      loc='audit-log/page.tsx:54',
      detail='Appends unless page is 1, so paging Next to 3 then Previous to 2 appends page 2 again on top of the accumulated list, producing duplicate React keys and repeated entries.',
      fix='Replace the list on every page change.'),
 dict(id='A-M14', sev='MEDIUM', status='open', cat='Error handling',
      title='Twelve pages swallow fetch errors into a "no data" empty state',
      loc='wallet, recycle-bin, fees, partners, partner-applications, referrals, deliveries, drivers, users, users/[id], fraud, cms, audit-log',
      detail='A 403 or a Railway cold start is indistinguishable from a clean board. wallet shows an all-zero money summary; recycle-bin, a compliance surface, says "Recycle bin is empty".',
      fix='Keep an error state and render a retry banner, as /duplicates, /insurance, /interstate and /identity already do.'),
 dict(id='A-M15', sev='MEDIUM', status='open', cat='Session',
      title='No global 401 handling',
      loc='src/lib/api.ts:16-19, lib/auth.ts:43, auth.service.ts:729',
      detail='req() throws a generic Error on any non-ok response and nothing inspects the status. With an 8-hour cookie against a 30-minute JWT, a tab left closed for 40 minutes passes middleware, then every request 401s into the silent catches above and the admin stares at empty pages.',
      fix='On 401, clearSession() and redirect to /login?reason=expired.'),
 dict(id='A-M16', sev='MEDIUM', status='open', cat='Dead controls',
      title='The Interstate Trip Board promises actions it does not have',
      loc='interstate/page.tsx:6-8,58,20',
      detail='Says ops can match orphaned long-haul packages and override allocations. The page is read-only: no match control, no link to a package, no link to the driver, and the driver phone is typed but never rendered. The status filter is hardcoded to active though the API accepts completed and cancelled.',
      fix='Build the actions or correct the copy.'),
 dict(id='A-M17', sev='MEDIUM', status='open', cat='Dead controls',
      title='Liability disputes are unreachable from a delivery',
      loc='disputes/page.tsx:93, deliveries/[id]/page.tsx',
      detail='The page asks the admin to paste a UUID "from delivery detail page", but the delivery detail page never displays the id: it shows trackingCode.',
      fix='Add an "Open chain of custody" link on the delivery detail page.'),
 dict(id='A-M18', sev='MEDIUM', status='open', cat='Admin-tunable',
      title='The liability matrix is hardcoded in the dashboard',
      loc='disputes/page.tsx:217-223',
      detail='Seven liability rules hardcoded as a table. This is a policy the founder has re-specified before; per the admin-tunable rule it should be config-backed with a code fallback.',
      fix='Move to the Fee Catalogue or a config row.'),
 dict(id='A-M19', sev='MEDIUM', status='open', cat='Admin-tunable',
      title='The 80% acceptance threshold is hardcoded',
      loc='last-order-compliance/page.tsx:25', detail='Drives both the summary card and the copy.', fix='Make it a Fee Catalogue row.'),
 dict(id='A-M20', sev='MEDIUM', status='open', cat='Permissions',
      title='Saving the Super Admin role converts its wildcard into an enumerated list',
      loc='roles/page.tsx:96,134, roles.service.ts:76',
      detail="The editor expands '*' to every permission slug on open and save() posts the expanded array, which the service accepts for system roles without protection. After one accidental save the super_admin role no longer matches permissions.includes('*'), and every page added later needs an explicit grant.",
      fix="Keep '*' when the full catalogue is selected, or reject permissions edits on system roles."),
 dict(id='A-M21', sev='MEDIUM', status='open', cat='Wrong data',
      title='The nav fraud badge is dead config',
      loc='rbac.ts:136, AdminNav.tsx:190',
      detail="rbac declares badge 'fraud' but the nav renders only badge === 'tickets'. The file own comment records that this exact bug was already fixed once for tickets. Open fraud flags are invisible until someone opens the page.",
      fix='Render the fraud badge.'),
 dict(id='A-M22', sev='MEDIUM', status='open', cat='UX',
      title='Nine destructive or audited actions use browser prompt/confirm/alert',
      loc='dev-accounts, drivers/[id] (the two-person-rule level change and its audited reason), identity (rejection and revocation reasons shown to users), partner-applications, partners, partners/[id], settings, support (bank and vehicle change approvals)',
      detail='users/[id]:103 documents the decision to stop doing this. prompt() is blocked outright in some browser configurations, which would make those flows unusable.',
      fix="Use the app's ConfirmDialog."),
 dict(id='A-M23', sev='MEDIUM', status='open', cat='Dead code',
      title='Fourteen API methods are dead code against live backend routes',
      loc='src/lib/api.ts',
      detail='pricing.get/update (a whole second pricing config the dashboard never opens), payments.refund, suspendUser, pendingDeletions.softDelete, tickets.list/get/update/reply, analytics.heatmap, websiteContent.get, identityVerifications.get, roles.get, fees.get/grouped. Each is a maintained endpoint with no consumer.',
      fix='Wire or delete.'),
 dict(id='A-M24', sev='MEDIUM', status='open', cat='Wrong data',
      title='"Deliveries by Category" is actually urgency',
      loc='analytics/page.tsx:210, admin.service.ts:1807-1814',
      detail='The pie is labelled by category but the query groups by d.urgency, and the backend comment says so. The legend will read express/standard, not cargo categories.',
      fix='Group by categoryCode or rename the chart.'),
 dict(id='A-L1', sev='LOW', status='open', cat='Copy',
      title='Em-dash in user-visible copy',
      loc='components/SosBanner.tsx:37, instrumentation.ts:1', detail='The only two in the project.', fix='Replace.'),
 dict(id='A-L2', sev='LOW', status='open', cat='Dead controls',
      title='dev-docs primary CTA links to a placeholder domain',
      loc='dev-docs/page.tsx:36-44,73', detail='"Open docs.seirs.app" on a domain the same page admits is a placeholder. A nav entry whose main button goes nowhere.', fix='Hide until the docs exist.'),
 dict(id='A-L3', sev='LOW', status='open', cat='Dead controls',
      title='/partner-redirects is a nav entry to a feature with no backend',
      loc='partner-redirects/page.tsx', detail='Renders three fake preview rows. Honestly labelled "Not available at launch", but occupies a permanent slot for ops_manager and partner_manager.', fix='Hide behind a flag.'),
 dict(id='A-L4', sev='LOW', status='open', cat='Copy',
      title='A date range renders as two sentences',
      loc='promotions/page.tsx:157', detail='"05 Aug 2026. 05 Sep 2026".', fix='Use "to".'),
 dict(id='A-L5', sev='LOW', status='open', cat='Dead code',
      title='An unreachable specific_zone audience that would throw if selected',
      loc='notify/page.tsx:174,65,307,115',
      detail='specific_zone is handled but absent from AUDIENCES, so the zone input and preview branch are unreachable, and the non-null find at 115 would throw if it ever were selected.', fix='Remove or add it properly.'),
 dict(id='A-L6', sev='LOW', status='open', cat='Wrong data',
      title='The commission label always shows one decimal',
      loc='app/page.tsx:141', detail='A float-modulo test (rate % 0.01 === 0) that is essentially never true, so it always renders "15.0% of gross revenue".', fix='Round properly.'),
 dict(id='A-L7', sev='LOW', status='open', cat='Wrong data',
      title='Fees whose category is not in a hardcoded list are silently hidden',
      loc='fees/page.tsx:204', detail='CATEGORY_ORDER currently matches all 13 enum members exactly, so nothing is hidden today, but a new backend category would be invisible with no error.', fix='Fall back to rendering unknown categories.'),
 dict(id='A-L8', sev='LOW', status='open', cat='Dead code',
      title='Middleware special-cases a /track route that does not exist',
      loc='src/middleware.ts:91', detail='No app/track/**/page.tsx exists.', fix='Remove.'),
 dict(id='A-L9', sev='LOW', status='open', cat='Comments',
      title='Contradictory comments about the token refresh interval',
      loc='src/lib/api.ts:25 vs components/NavWrapper.tsx:12-16', detail='One says ~5 minutes, the other says 10 and 10 is what runs.', fix='Fix the comment.'),
 dict(id='A-L10', sev='LOW', status='open', cat='Comments',
      title='Stale "placeholder route" comment',
      loc='notify/page.tsx:11-13', detail='Both notification routes are real and both used.', fix='Delete.'),
 dict(id='A-L11', sev='LOW', status='open', cat='UX',
      title='An entered 0 silently becomes 60, and invalid nested clickables',
      loc='dev-accounts/page.tsx:71,152-160',
      detail='Math.max/min with a || 60 fallback turns 0 into 60. A clickable span is nested inside a button, which is invalid HTML and not keyboard-reachable.', fix='Handle 0 and unnest.'),
 dict(id='A-L12', sev='LOW', status='open', cat='Wrong data',
      title='A brand-new driver renders as 0.0 stars',
      loc='drivers/page.tsx:131', detail='Number(null).toFixed(1) reads as a terrible driver rather than "no ratings yet". last-order-compliance handles the same case correctly with a dash.', fix='Render a dash.'),
 dict(id='A-L13', sev='LOW', status='open', cat='Dead code',
      title='A computed super-admin check that is never referenced',
      loc='users/[id]/page.tsx:33', detail='See A-H17: the guard was written and not wired.', fix='Use it.'),
 dict(id='A-D1', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='Three build breaks in the dashboard',
      loc='drivers/[id]/page.tsx:425, src/lib/api.ts, app/page.tsx:66',
      detail='A multiline single-quoted string broke the webpack parse; adminApi.revenueSplit was called but never defined on the client; and the Promise.all destructure ignored the inserted element so the revenue tiles would have rendered blank. None of these would have deployed.',
      fix='Template literal, added the client method, fixed the destructure. next build now exits 0.'),
]
