# -*- coding: utf-8 -*-
"""Business app findings."""
APP = 'Business app'
KEY = 'business'
FINDINGS = [
 dict(id='B-1.1', sev='HIGH', status='open', cat='Dead controls',
      title='Drawer "Team Members" navigates to a route with no file',
      loc='components/Drawer.tsx:54',
      detail='navigate("/(business)/team"). There is no app/(business)/team.tsx and the route is absent from the generated router union. Team management is a headline business feature; tapping it dead-ends on +not-found.',
      fix='Build the screen, or remove the row until it exists.'),
 dict(id='B-1.2', sev='HIGH', status='open', cat='Dead controls',
      title='Drawer "Billing & Invoices" opens the Rewards tab, not invoices',
      loc='components/Drawer.tsx:55',
      detail='navigate("/(business)/wallet") while app/(business)/billing.tsx exists and the Profile tab routes to it correctly. This is a regression of a bug the founder already reported: billing.tsx:4-7 records that the Profile row of this name opened Rewards and there was no invoices screen at all. The Profile row was fixed; the drawer row was not.',
      fix='navigate("/(business)/billing").'),
 dict(id='B-1.3', sev='MEDIUM', status='open', cat='Dead controls',
      title='"Special Cargo" and "Send a Package" are the same button',
      loc='app/(business)/(tabs)/index.tsx:115-120',
      detail='Both ActionCards push /(business)/send-package with no distinguishing param, and send-package reads no route params. The subtitle promises "Trucks, cold chain & heavy loads" but nothing preselects a truck or a cold-chain category.',
      fix='Pass params { preset: "cargo" } and preselect truck_small, or drop the third card.'),
 dict(id='B-1.4', sev='MEDIUM', status='open', cat='Dead controls',
      title='Notification rows are pressable but go nowhere',
      loc='app/(business)/notifications.tsx:179-181',
      detail='onPress only marks one read, so a "package delivered" notification just un-bolds itself.',
      fix='Route on item.type to the delivery when the payload carries an id.'),
 dict(id='B-1.5', sev='LOW', status='open', cat='Dead controls',
      title='Dead QR modal in the Profile tab',
      loc='app/(business)/(tabs)/profile.tsx:30,174-184',
      detail='qrVisible is only ever set false; nothing sets it true. The whole Modal and the QRCode import are unreachable; the ID row pushes to /(business)/seirs-id instead.',
      fix='Delete the modal and the import.'),
 dict(id='B-2.1', sev='MEDIUM', status='open', cat='Mock data',
      title='Sponsored Placement metrics are hardcoded zeros for a paying partner',
      loc='app/(partner)/billing.tsx:88-90',
      detail='impressions and clickThroughs are literal 0 in BOTH branches, yet the page sells "Live impression + click-through dashboard updated daily", and the "Activate to start collecting placement metrics" hint only renders when INACTIVE. A partner who pays the monthly fee sees a permanent 0/0 ROI panel with no explanation.',
      fix='Render a dash with "Impression tracking ships with the placement_impressions table" until it is real.'),
 dict(id='B-2.2', sev='MEDIUM', status='open', cat='Mock data',
      title='Partner dashboard invents a capacity of 50 when the fetch fails',
      loc='app/(partner)/index.tsx:27-36',
      detail='The catch swallows the error, then capacity = data?.maxCapacity ?? 50 drives the "0 / 50 packages" readout and the percentage bar. A server outage is indistinguishable from an empty, correctly-configured store.',
      fix='Hold error state and render "Could not load store status" instead of a fabricated denominator.'),
 dict(id='B-2.3', sev='MEDIUM', status='open', cat='Mock data',
      title='Deliveries list shows raw backend vehicle enums, not Nigerian vocabulary',
      loc='app/(business)/(tabs)/deliveries.tsx:214',
      detail='Prints "motorcycle", "tricycle", "van", "truck small". The booking wizard VEHICLE_LABEL maps these to Okada / Keke / Danfo. A business books an Okada and the list calls it a motorcycle.',
      fix='Import and apply VEHICLE_LABEL here.'),
 dict(id='B-2.4', sev='LOW', status='open', cat='Mock data',
      title='Fallback hero cards are badged NEW and dated three months ago',
      loc='constants/heroCards.ts:120-123',
      detail='badgeKey NEW with publishedAt 2026-05-15, which relativeDate renders as "3 months ago". Whenever the CMS is empty or offline the carousel shows stale NEW content.',
      fix='Omit publishedAt on the built-in fallbacks.'),
 dict(id='B-3.1', sev='LOW', status='open', cat='Unwired API',
      title='Three screens bypass the barrel whitelist by design',
      loc='api-keys.tsx:10, api-usage.tsx:8, webhook-log.tsx:9',
      detail='They import request straight from the shared module. It works, but request is not in the whitelist, so these three sidestep the guardrail. NOTE: the barrel category is otherwise fully CLEAN across all 84 imports.',
      fix='Route through the barrel or document the exception.'),
 dict(id='B-4.1', sev='MEDIUM', status='open', cat='No-wallet rule',
      title='The Wallet tab still calls the retired wallet endpoint and throws the answer away',
      loc='app/(business)/(tabs)/wallet.tsx:38,47,56',
      detail='businessApi.wallet() fires on every mount, lands in setWallet, and wallet is never read again. A retired ledger endpoint kept warm in production traffic for nothing.',
      fix='Delete the state and the call.'),
 dict(id='B-4.2', sev='MEDIUM', status='open', cat='No-wallet rule',
      title='A sender Rewards screen is titled "Wallet"',
      loc='app/(business)/(tabs)/wallet.tsx:89',
      detail='Hardcodes the heading "Wallet" for both roles, while the tab bar correctly labels it Rewards for senders. A sender taps a tab that says Rewards and lands on a screen headed Wallet.',
      fix="{isPartner ? 'Wallet' : 'Rewards'}."),
 dict(id='B-4.3', sev='MEDIUM', status='open', cat='No-wallet rule',
      title='The documents statement prints a "Wallet top-ups" line to an accountant',
      loc='app/(business)/documents.tsx:67,69',
      detail='Reads "Wallet top-ups: N X" and "Figures aggregate your SEIRS business wallet transactions". This goes into a file the business hands to its accountant and to FIRS, asserting a wallet relationship that does not exist.',
      fix='Drop the line and reword to "delivery payments made through SEIRS".'),
 dict(id='B-4.4', sev='LOW', status='open', cat='No-wallet rule',
      title='Orphaned wallet fields and a deleted button stylesheet',
      loc='csv-upload.tsx:62-63, (tabs)/index.tsx:252-263',
      detail='walletBalance and canAfford remain in the response interface, neither rendered. walletCard, walletLabel, walletBalance, fundBtn and fundBtnText styles survive their deleted JSX: a literal fund-wallet button stylesheet.',
      fix='Remove.'),
 dict(id='B-5.1', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='The partner tab bar has no bottom-inset floor',
      loc='app/(partner)/_layout.tsx:34-35',
      detail='height 56 + insets.bottom and paddingBottom insets.bottom. The business tab bar solved exactly this with Math.max(insets.bottom, 8) and its comment explains why: on button-nav Androids insets.bottom is 0 so the bar has no cushion. The partner bar never got the fix and sits flush against the phone navigation.',
      fix='Apply Math.max(insets.bottom, 8) to both lines.'),
 dict(id='B-5.2', sev='LOW', status='open', cat='Keyboard and layout',
      title='Partner opening-hours fields have no keyboardType',
      loc='app/(partner)/settings.tsx:170-176,180-186',
      detail='"Opens At" / "Closes At" with placeholders 08:00 and 18:00 open the full alpha keyboard.',
      fix='keyboardType="numbers-and-punctuation".'),
 dict(id='B-6.1', sev='HIGH', status='open', cat='Copy',
      title='The full-screen map legend prints a Google ETA, which the same file bans 330 lines earlier',
      loc='app/(business)/send-package.tsx:1850',
      detail='Renders route.durationText. The thumbnail version at 1519 deliberately omits it, with the comment "Kilometres only: minutes are a promise this platform does not make (founder rule)." The expanded map breaks the rule the collapsed one states.',
      fix='Delete the route.durationText clause.'),
 dict(id='B-6.2', sev='MEDIUM', status='open', cat='Copy',
      title='"Driver arrives ... around 9 AM"',
      loc='app/(business)/send-package.tsx:1396',
      detail='This is a scheduled pickup hour the sender chose, but the word is ARRIVES, and Lagos traffic makes it a refund magnet.',
      fix='"Pickup is booked for today, around 9 AM."'),
 dict(id='B-6.3', sev='HIGH', status='open', cat='Copy',
      title='The Terms of Service consent link points at a domain the app never otherwise uses',
      loc='app/(business)/send-package.tsx:1659',
      detail='Linking.openURL("https://seirs.app/terms-of-service"). Every other legal/FAQ link in the app uses seirs-website.vercel.app. This is the "Read them" link inside the checkbox that legally gates payment.',
      fix='Settle the canonical domain (see W-4) and use one shared constant.'),
 dict(id='B-6.4', sev='HIGH', status='open', cat='Copy',
      title='The recipient collection link is on the same unresolved domain',
      loc='app/(business)/delivery/[id].tsx:123',
      detail='"Settle the collection fee and get the pickup address here: https://seirs.app/collect/<code>". This is shared out to the RECIPIENT to pay a redirect fee and reveal the pickup address. If seirs.app does not resolve, the fee is never settled and the parcel sits on a partner shelf accruing storage.',
      fix='Point at the live host and verify /collect/{code} exists there before shipping.'),
 dict(id='B-6.5', sev='LOW', status='open', cat='Copy',
      title='14 em-dash characters in comments (banned project-wide)',
      loc='utils/articleMeta.ts, store/businessStore.ts, constants/nigerian-states.ts, constants/config.ts, i18n/index.ts, hooks/use-bookmarks.ts, send-package.tsx:2',
      detail='None reach the user, but the ban is project-wide.', fix='Replace.'),
 dict(id='B-6.6', sev='LOW', status='open', cat='Copy',
      title='Phone validation regex and its error message disagree',
      loc='app/(auth)/register.tsx:63 vs :77',
      detail='The regex accepts 071 but the error lists only 080, 081, 070, 090 or 091. A Glo 071 user who mistypes is told 071 is invalid.', fix='Align them.'),
 dict(id='B-7.1', sev='HIGH', status='open', cat='Icon registry',
      title='Six icon names are missing from the registry and render as NOTHING',
      loc='components/Icon.tsx:21-38 (registry) and 8 call sites',
      detail='Icon returns null for an unknown name with only a __DEV__ warning. Missing: AlertTriangle (the SOS Emergency drawer row, the most safety-critical control in the app, and the seirs-id security warning), QrCode ("My SEIRS ID" in BOTH sender and partner drawers), ShieldCheck (verified-identity card, policy documents), FileSignature (contract documents), Flag ("Report an issue"), File (every "other" document AND the fallback at documents.tsx:181, so an unrecognised category is doubly invisible). This is the third time this registry has been under-filled.',
      fix='Add the six to the import block and the ICONS map, and adopt the FALLBACK pattern Illustration.tsx already uses so something always renders.'),
 dict(id='B-8.1', sev='MEDIUM', status='open', cat='Unreachable',
      title='Four fully-built screens have no entry point anywhere',
      loc='api-keys.tsx (258 lines), api-usage.tsx (129), webhook-log.tsx (155), recurring.tsx (490)',
      detail='No drawer row, no tab, no router.push, no Link. api-keys issues live API keys that, per its own line 118, "charge real money". recurring.tsx is a complete Spec V8 recurring-delivery scheduler wired to a live backend cron.',
      fix='Add a Developer section to the sender drawer for the trio, and a Recurring Deliveries row.'),
 dict(id='B-8.2', sev='MEDIUM', status='open', cat='Unreachable',
      title='Partners have no SOS',
      loc='components/Drawer.tsx:81-92',
      detail='partnerItems omits the SOS row senderItems has. sos.tsx records the founder intent verbatim: "we do not know who may need it... if they feel unsafe and they have the SEIRS app they should be able to press it." A shopkeeper alone at a counter is arguably the most exposed user on the platform.',
      fix='Add the same SOS entry to partnerItems.'),
 dict(id='B-8.3', sev='MEDIUM', status='open', cat='Unreachable',
      title='webhook-log instructs the user to use a control that does not exist',
      loc='app/(business)/webhook-log.tsx:82',
      detail='"Subscribe to events from the API Keys page". api-keys.tsx only issues, copies and revokes keys; there is no endpoint-subscription UI at all.', fix='Build it or change the copy.'),
 dict(id='B-9.1', sev='MEDIUM', status='open', cat='Comments',
      title='csv-upload comment describes the retired wallet path',
      loc='app/(business)/csv-upload.tsx:12',
      detail='"Wallet debit + Delivery + DeliveryStop rows created atomically per booking". The code at 128-131 explicitly removed it. Line 236-240 in the same file WAS updated, so this one was simply missed.', fix='Rewrite.'),
 dict(id='B-9.2', sev='LOW', status='open', cat='Comments',
      title='Four more stale or contradictory comments',
      loc='(tabs)/_layout.tsx:71; send-package.tsx:490-491; (tabs)/profile.tsx:172-173; partner/billing.tsx:16',
      detail='Tab labels "step up to 12" when the code sets 11; Google distance "replaces the estimate" when it replaces it for display only; a comment describing the dead QR modal; and a standing TODO whose screen simultaneously says "no card is charged" and "Auto-billed monthly via Flutterwave".',
      fix='Rewrite or resolve.'),
 dict(id='B-9.3', sev='LOW', status='open', cat='Comments',
      title='api-usage renders a "what we will track" list of five unbuilt features',
      loc='app/(business)/api-usage.tsx:66,71',
      detail='"ship in the next batch", contradicting the act-like-the-app-is-live rule.', fix='Remove the card until the tracking exists.'),
 dict(id='B-9.4', sev='LOW', status='open', cat='Comments',
      title='Dead code and misnamed styles',
      loc='(tabs)/index.tsx:16-17,225-230; send-package.tsx:1903-1904; deliveries.tsx:396,399; wallet.tsx:261-265; StatePicker.tsx:141; partner/index.tsx:251; constants/heroCards.ts:83-84',
      detail='Unused fmt and getTimeOfDay; superseded errorBox/errorText; unused cancelLink; unused noteCard; inlined rowPressed; a style named logoutBtn that now opens the drawer; ctaKey/ctaRoute declared and documented but never set or read.',
      fix='Remove.'),
 dict(id='B-10.1', sev='HIGH', status='open', cat='Session',
      title='The session-expiry handler is never registered in this app',
      loc='context/AuthContext.tsx',
      detail='The business AuthProvider never calls setSessionExpiredHandler; both sibling apps do. On a 401 the shared client clears the token, calls onSessionExpired (null here) and throws. Because isAuthenticated derives from in-memory user state it stays true, NavigationGuard never fires, and the user is stranded inside a fully rendered but EMPTY app: dashboard zeros, "No deliveries found", 0 points. Every screen has a catch that swallows the error, so nothing tells them to sign in again. Only a force-quit recovers. Exactly the defect a device sweep cannot catch: it needs an expired token.',
      fix='Mirror the customer app: setSessionExpiredHandler(() => { setUser(null); router.replace("/(auth)/login"); }).'),
 dict(id='B-10.2', sev='HIGH', status='open', cat='Money',
      title='CSV bulk upload "Confirm N480,000" charges nothing and never says so',
      loc='app/(business)/csv-upload.tsx:323-331,121-170,302-313',
      detail='The CTA is labelled with the grand total. confirmCreate creates the deliveries and sets step done; the done card says only "Created N bookings" and offers "View Deliveries". No checkout is ever opened and the word unpaid appears nowhere, while the screen own instruction at 240 promises "Tap Confirm to create the deliveries, then pay for the batch". A business uploads 40 bookings, taps a button showing N480,000, and believes it is settled.',
      fix='Rename to "Create N bookings (N X to pay)" and make the done card say they are awaiting payment.'),
 dict(id='B-10.3', sev='MEDIUM', status='open', cat='Money',
      title='CSV bookings bypass the consent gate and the quote pin',
      loc='app/(business)/csv-upload.tsx:142-162',
      detail='Calls createDelivery with no termsAccepted and no quoteToken, both of which send-package sends. Bulk bookings capture no consent to the failed-delivery terms, and the total on the Confirm button is unpinned so the server can legitimately charge something else.',
      fix='Add the consent checkbox and thread the preview quote token through.'),
 dict(id='B-10.4', sev='MEDIUM', status='open', cat='Money',
      title='The quote is priced on straight-line distance while the review displays road distance',
      loc='app/(business)/send-package.tsx:526,541,743',
      detail='Sends km: totalKm (crow-flies x 1.45) but the effect dependency lists routeKm, so when Directions resolves the effect re-fires and re-quotes with the SAME stale number, burning the quote pin. Meanwhile the screen displays route.distanceText and handleSubmit books with km: routeKm. Quoted on one distance, displayed and booked on another.',
      fix='Change line 526 to km: routeKm.'),
 dict(id='B-10.5', sev='MEDIUM', status='open', cat='Other',
      title='KYC documents upload without the kyc folder',
      loc='app/(business)/apply-partner.tsx:95-97',
      detail='Three bare uploadApi.file(uri) calls carrying the owner government ID, the CAC certificate and the storefront photo. folder is optional and omitted entirely when absent, so these land unsegregated while UploadFolder defines "kyc" for precisely this. Every other upload in the app passes one.',
      fix="uploadApi.file(uri, 'image/jpeg', 'kyc')."),
 dict(id='B-10.6', sev='MEDIUM', status='open', cat='Other',
      title='Partner handover proof photos pass an argument that is silently discarded',
      loc='app/(partner)/receive-dropoff.tsx:181, release-pickup.tsx:183',
      detail='uploadApi.uploadFile(photoUri, "partner-receive"). That second parameter is _prefix and is explicitly ignored. These are chain-of-custody photos for a counter handover, and the code reads as though it files them by prefix when it does not.',
      fix="uploadApi.file(photoUri, 'image/jpeg', 'proof')."),
 dict(id='B-10.7', sev='MEDIUM', status='open', cat='Other',
      title='Partner notification toggles contradict the Profile tab stated policy',
      loc='app/(partner)/settings.tsx:194-211 vs (tabs)/profile.tsx:93-96',
      detail='Settings offers three per-event switches while Profile deliberately removed the Notifications row on the grounds that everything always sends, and notifications.tsx notes push has not shipped. Today a partner can switch off "Payout Processed" and nothing changes.',
      fix='Pick one position.'),
 dict(id='B-10.8', sev='MEDIUM', status='open', cat='Other',
      title='Five hardcoded light panels glare in dark mode',
      loc='api-keys.tsx:125,228; api-usage.tsx:121-122; seirs-id.tsx:174; csv-upload.tsx:479',
      detail='No theme override at the use site, so they render pale on a dark screen. api-keys:228 is the one-time secret reveal. partner/index.tsx documents this exact class as a founder finding and fixes it there with an isDark ternary; these five were missed.',
      fix='Apply the same isDark pattern.'),
 dict(id='B-10.9', sev='LOW', status='open', cat='Other',
      title='A failed deliveries fetch becomes an unhandled rejection',
      loc='app/(business)/(tabs)/deliveries.tsx:75-87',
      detail='load() uses try/finally with no catch, so the list silently keeps its previous contents.', fix='Add a catch and an error state.'),
 dict(id='B-10.10', sev='LOW', status='open', cat='Other',
      title='A Camera icon that only opens the photo library',
      loc='app/(business)/send-package.tsx:874-880,415',
      detail='pickPhoto only calls launchImageLibraryAsync. There is no way to photograph the parcel in the moment: the sender must leave, use the camera app, and come back.',
      fix='Offer a capture option.'),
 dict(id='B-D1', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='The consent passthrough shipped that morning did not typecheck',
      loc='shared/services/api.ts businessApi.createDelivery',
      detail='termsAccepted and quoteToken were being SENT by send-package.tsx but neither was declared on the body type, so the business app tsc failed. It was shipped after running only the backend and admin builds, never the business app own typecheck.',
      fix='Declared both fields. Business app now typechecks clean.'),
]
