# -*- coding: utf-8 -*-
"""Customer app findings. status: closed | open | decision"""
APP = 'Customer app'
KEY = 'customer'
FINDINGS = [
 # ── dead controls / theatre ──────────────────────────────────────────────
 dict(id='C-1.1', sev='HIGH', status='closed', cat='Dead controls',
      title='Drawer "Send Multiple" navigated to a route that does not exist',
      loc='components/Drawer.tsx:48',
      detail='navigate("/(customer)/business"). No such file, and the generated router type union contains zero occurrences of "business". One of six drawer items was a dead end; on device it simply closed the drawer and did nothing.',
      fix='Repointed at /(customer)/send, which IS the multi-package flow.'),
 dict(id='C-1.2', sev='HIGH', status='closed', cat='Dead controls',
      title='SOS Quick Dial said it was calling and called nothing',
      loc='app/(customer)/sos.tsx:177-188',
      detail='onPress showed Alert "Calling Police (199)..." and placed no call. Linking was not even imported in the file. In an emergency this is the worst possible lie.',
      fix='Imported Linking, onPress now opens tel: with an Alert fallback.'),
 dict(id='C-1.3', sev='HIGH', status='open', cat='Dead controls',
      title='"Apply Code" permanently burns the promo and never reaches checkout',
      loc='app/(customer)/promo.tsx:55',
      detail='Calls promotionsApi.redeem({code, subtotalKobo: 0}). The backend redeem() is a real redemption, not a validation: it counts against perUserLimit, persists a redemption row and increments the campaign-wide usageCount. With subtotal 0 the discount applies to nothing. No booking flow anywhere reads a promo code, so the promised checkout does not exist. Two harms: the customer loses their one allowed use and is told the opposite, and anyone can drain a campaign usageLimit from this screen without booking.',
      fix='Add a validate-only endpoint (or dryRun flag) and call that; persist the accepted code into the booking store and pass it to deliveriesApi.create.'),
 dict(id='C-1.4', sev='MEDIUM', status='open', cat='Dead controls',
      title='share-trip "Copy" button never copies',
      loc='app/(customer)/share-trip.tsx:55-58',
      detail='handleShare("copy") sets copied=true for 2s and returns. The label flips to "Copied!" with a checkmark and the clipboard is untouched. expo-clipboard is a dependency used correctly in 8 other screens.',
      fix='await Clipboard.setStringAsync(shareLink) before setCopied(true).'),
 dict(id='C-1.5', sev='MEDIUM', status='open', cat='Dead controls',
      title='Profile fetches the wallet on every focus and renders nothing',
      loc='app/(customer)/(tabs)/profile.tsx:31,53,59',
      detail='walletBalance is set from paymentsApi.wallet() and never read. The comment at 217-221 explains the wallet cell was removed; the fetch was not. A wasted round-trip on every tab focus.',
      fix='Delete the state and drop paymentsApi.wallet() from the Promise.all.'),
 dict(id='C-1.6', sev='MEDIUM', status='open', cat='Dead controls',
      title='Rewards tab fetches community pulse and renders nothing',
      loc='app/(customer)/(tabs)/wallet.tsx:55,66,77',
      detail='pulse is set from deliveriesApi.communityPulse(); the section was removed. Styles pulseCard/pulseIcon/pulseCount/pulseCountUnit/pulseSub are dead too.',
      fix='Remove the state, the call and the five styles.'),
 dict(id='C-1.7', sev='MEDIUM', status='open', cat='Dead controls',
      title='Home runs a scroll animation for buttons that no longer exist',
      loc='app/(customer)/(tabs)/index.tsx:63-95,147',
      detail='onScroll with scrollEventThrottle 16 drives hideFabs/showFabs animating fabTranslate; nothing renders it (FABs removed). animateAndGo, sendWidth, rideWidth have one reference each. Styles fabPair/fabRow/fabPressable/fabLabel and drawerOverlay..drawerSignOutText are dead.',
      fix='Delete onScroll/scrollEventThrottle, lines 60-95 and the dead styles.'),
 dict(id='C-1.8', sev='MEDIUM', status='open', cat='Dead controls',
      title='Transaction detail has a share button with no onPress',
      loc='app/(customer)/transaction/[id].tsx:48-50', detail='A Pressable with a share icon and no handler.',
      fix='Wire it to Share.share or remove it.'),
 dict(id='C-1.9', sev='MEDIUM', status='open', cat='Dead controls',
      title='Rating submit failure is invisible',
      loc='components/RatingModal.tsx:31-33',
      detail='On throw, setSubmitted(true) is skipped and the catch is empty. The spinner stops, the form reappears, no message.',
      fix='Surface the error in the modal.'),
 dict(id='C-1.10', sev='MEDIUM', status='open', cat='Dead controls',
      title='Privacy screen has a loaded-but-unrendered toggle',
      loc='app/(customer)/privacy.tsx:57,67,81',
      detail='personalisedAds is read from the server and onTogglePersonalised exists, but no ToggleRow renders it. PRIVACY_PREF_KEYS is declared with an explanatory comment and never used.',
      fix='Render the row or delete the state.'),
 # ── mock values ──────────────────────────────────────────────────────────
 dict(id='C-2.1', sev='HIGH', status='open', cat='Mock data',
      title='share-trip shows a fabricated pickup and dropoff',
      loc='app/(customer)/share-trip.tsx:31',
      detail='MOCK_TRIPS.find(tr => tr.id === id) ?? MOCK_TRIPS[2]. Real deliveries have UUIDs so find always misses and trip becomes the fictional Surulere to Ajah trip, rendered verbatim on the share card. Worst path: Drawer, SOS, "Share My Live Location" passes an undefined deliveryId, so a user sharing their location during an emergency shares someone else invented route. A 2026-08-15 sweep fixed the tracking code here and left the addresses.',
      fix='In the .then at 42-44 also setFetchedTrip(d) and render fetchedTrip?.pickupAddress instead of trip.pickupAddress.'),
 dict(id='C-2.2', sev='MEDIUM', status='open', cat='Mock data',
      title='MOCK_VEHICLES fallback mislabels every cargo vehicle',
      loc='app/(customer)/fare-breakdown.tsx:54',
      detail='MOCK_VEHICLES ids are economy/premium/truck; the cargo picker passes bicycle/motorcycle/keke/car/van/truck_sm/truck_lg, so the lookup can never hit and it renders "Economy / Affordable everyday rides / 4 min" regardless. A landmine rather than a live bug because the cargo branch is unreachable (C-6.1).',
      fix='Delete the screen or map ids properly.'),
 dict(id='C-2.3', sev='MEDIUM', status='open', cat='Mock data',
      title='trip-progress falls back to mock trip and mock driver',
      loc='app/(customer)/trip-progress.tsx:79,82,92',
      detail='mockTrip ?? MOCK_TRIPS[2], MOCK_DRIVERS[0], and eta: mockDriver.eta (hardcoded 4) is used even when a real driver was fetched. Unreachable today (C-6.2).',
      fix='Delete the screen.'),
 dict(id='C-2.4', sev='MEDIUM', status='open', cat='Mock data',
      title='Transaction detail is 100% mock',
      loc='app/(customer)/transaction/[id].tsx:31',
      detail='MOCK_TRANSACTIONS.find(...) ?? MOCK_TRANSACTIONS[0], rendering "Wallet Top-up +N20,000 Bank Transfer success" as a real transaction. Unreachable today.',
      fix='Delete the screen or wire it to the real ledger.'),
 dict(id='C-2.5', sev='MEDIUM', status='open', cat='Mock data',
      title='Bundled article content carries stale dated promos and fabricated partnership claims',
      loc='constants/heroCards.ts:16, i18n/locales/en.json:288-296',
      detail='The file states the contract: keep it evergreen, no dated promos, since changing it needs an app release. The data below it says "Up to 25% off your first three orders this week" and "Shoprite Surulere and Lekki branches open next month, followed by Ikoyi in July. We are also in talks with Spar and ShopRite Apapa." publishedAt is 2026-05-17, so those dates are three months past, and it names real retailers with partnership claims.',
      fix='Rewrite evergreen or move to the CMS.'),
 dict(id='C-2.6', sev='MEDIUM', status='open', cat='Mock data',
      title='Fabricated performance statistic',
      loc='i18n/locales/en.json:311',
      detail='"Customers who schedule even 60 minutes ahead see deliveries arrive 18 minutes faster on average." No such data exists pre-launch, and it is also a delivery-speed claim.',
      fix='Delete the sentence.'),
 # ── unwired api ──────────────────────────────────────────────────────────
 dict(id='C-3.1', sev='HIGH', status='closed', cat='Unwired API',
      title='usersApi.saveNotificationPrefs does not exist; both toggles threw',
      loc='app/(customer)/notification-settings.tsx:57,111',
      detail='The method exists nowhere in the monorepo (confirmed by exhaustive repo-wide search). Calling undefined throws synchronously BEFORE a promise exists, so .catch cannot help. The privacy switch threw inside onValueChange (render-phase, red screen); the marketing switch threw inside a setTimeout as an unhandled exception. Neither preference had ever saved. This included the anonymity toggle shipped the same morning.',
      fix='Renamed both to usersApi.updateNotificationPrefs, which exists and is already used correctly by privacy.tsx:76.'),
 # ── keyboard / layout ────────────────────────────────────────────────────
 dict(id='C-4.1', sev='HIGH', status='closed', cat='Keyboard and layout',
      title='The entire SOS screen was unreadable in light mode',
      loc='app/(customer)/sos.tsx:121 and all text styles',
      detail='Root background isDark ? #0A0000 : #FFF1F1 (near-white) while every text style is hardcoded white or translucent white. On #FFF1F1 all of it vanishes. A dark-mode device sweep never sees this; a daytime user in an emergency sees a blank red-tinted screen with a red circle.',
      fix='Deep red (#7F1D1D) ground in light mode too, so the white text reads in both themes. Verified on device.'),
 dict(id='C-4.2', sev='MEDIUM', status='closed', cat='Keyboard and layout',
      title='Send CTA used raw insets.bottom under a comment asserting the opposite',
      loc='app/(customer)/send.tsx:2015-2021',
      detail='Comment claimed insets.bottom is ~48dp on the 3-button layout. request.tsx:376-378 records the measured truth: it lies as 0 there. Send, the primary conversion flow, was left on the raw value.',
      fix='Math.max(insets.bottom, 24) and the comment now states what was measured.'),
 dict(id='C-4.3', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='Onboarding three CTAs use raw insets.bottom',
      loc='app/(auth)/onboarding.tsx:172',
      detail='paddingBottom: insets.bottom + Spacing.md. With insets.bottom 0 the "Become a Driver" button sits ~16px off the edge, under the nav bar. This is the first screen a new user ever sees.',
      fix='Math.max(insets.bottom, 24) + Spacing.md.'),
 dict(id='C-4.4', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='Tab bar uses raw insets.bottom',
      loc='app/(customer)/(tabs)/_layout.tsx:61-62',
      detail='height 64 + insets.bottom, paddingBottom 10 + insets.bottom. app.json has edgeToEdgeEnabled true, so with insets.bottom 0 the labels sit 10px from the physical edge.',
      fix='Math.max(insets.bottom, 12) in both.'),
 dict(id='C-4.5', sev='MEDIUM', status='closed', cat='Keyboard and layout',
      title='The keyboard covered the field being typed into',
      loc='app/(customer)/send.tsx:1008',
      detail='KeyboardAvoidingView behavior is undefined on Android and the CTA bar sits outside the ScrollView. Reproduced on the A30: tapping "What is it?" opened the keyboard straight over the input and the list never scrolled, so the sender could not see their own typing. The business Send solved this on 2026-08-16 and customer never got the fix.',
      fix='Ported the business lift: measureInWindow the focused node against the real keyboard top and scroll by the overlap, with the first focus handled in keyboardDidShow. Verified on device.'),
 dict(id='C-4.6', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='Documents modal bottom padding is thin',
      loc='app/(customer)/documents.tsx:115',
      detail='paddingBottom 20 + insets.bottom on a sheet whose Share/Close buttons are the last element. 20px floor is thin but not zero.',
      fix='Raise the floor to 24-28.'),
 # ── copy ─────────────────────────────────────────────────────────────────
 dict(id='C-5.1', sev='HIGH', status='open', cat='Copy',
      title='The app promises a 10% scheduling discount that does not exist',
      loc='i18n/locales/en.json:299 and :305',
      detail='"schedule the pickup an hour ahead. You get a 10% discount" and "The 10% discount applies automatically, no code". constants/rateCard.ts:443-449 enumerates every discount: bulkUploadOffPct 0.05 (min 50 packages), recurringOffPct 0.03, welcomeOffPct 0.10 (capped N300), loyalty points. There is no scheduling discount, and nothing in the backend matches either. A customer who schedules pays full price after being told twice it would be 10% less.',
      fix='Delete the two sentences, or add an admin-tunable scheduledAheadOffPct to the rate card and honour it.'),
 dict(id='C-5.2', sev='HIGH', status='closed', cat='Copy',
      title='SOS claimed emergency contacts are notified; they are not',
      loc='i18n/locales/en.json:842,845',
      detail='sos.service.ts fans out to all admins plus the other party on an active delivery. Nothing reads emergencyContactName/Phone, and per the no-SMS-at-launch policy nothing could. The user was asked to enter that contact on edit-profile, so they had every reason to believe it worked.',
      fix='Copy now names who is actually reached, corrected in all four locales.'),
 dict(id='C-5.3', sev='HIGH', status='closed', cat='Copy',
      title='Terms of Service link was a dead end',
      loc='app/(customer)/(tabs)/profile.tsx:123',
      detail='Linking.openURL to /terms. The website route is /terms-of-service. The .catch fallback never fires because openURL succeeds at opening a browser onto a 404.',
      fix='Repointed to /terms-of-service.'),
 dict(id='C-5.4', sev='MEDIUM', status='closed', cat='Copy',
      title='Dispute Resolution link 404s',
      loc='app/(customer)/privacy.tsx:246',
      detail='https://seirs.app/dispute-resolution. No such route exists on the site.',
      fix='Repointed at /terms-of-service, which carries the disputes section. Same fix applied to the driver app.'),
 dict(id='C-5.5', sev='MEDIUM', status='open', cat='Copy',
      title='Em-dash in user-visible copy (banned project-wide)',
      loc='app/(customer)/track.tsx:51',
      detail="picked_up: 'Arrived - meet them outside' uses an em-dash, rendered at line 493. 13 more sit in comments.",
      fix='Replace with a comma or colon.'),
 dict(id='C-5.6', sev='MEDIUM', status='open', cat='Copy',
      title='Version string is fabricated',
      loc='i18n/locales/en.json:1051',
      detail='"SEIRS Logistics v2.0.0 Build 204", rendered at profile.tsx:287. app.json says version 1.0.0. Support will ask what version the user is on and get a made-up answer. Duplicated across all four locales.',
      fix='Render from expo-constants.'),
 dict(id='C-5.7', sev='MEDIUM', status='closed', cat='Copy',
      title='SOS instruction contradicted the control',
      loc='i18n/locales/en.json:844, sos.tsx:140',
      detail='Copy said "Press and hold SOS button in an emergency" but the control uses onPress, a plain tap.',
      fix='Copy changed to "Tap SOS in an emergency" in all four locales.'),
 dict(id='C-5.8', sev='MEDIUM', status='decision', cat='Copy',
      title='SOS gives three different emergency numbers',
      loc='sos.tsx:24-25, en.json:857-858',
      detail='sos.tsx says Police 199; en.json callPolice says "Call Police (112)"; en.json says "call 199 directly"; sos.tsx assigns 112 to Ambulance. 112 is Nigeria national emergency number and 199 is commonly fire service.',
      fix='FOUNDER DECISION: confirm the correct number set before launch. I will not guess at numbers someone dials in a crisis.'),
 dict(id='C-5.9', sev='MEDIUM', status='open', cat='Copy',
      title='Card-removal dialog shows the empty-state text',
      loc='app/(customer)/payment-methods.tsx:65',
      detail='Passes paymentMethods.emptyDesc as the body of a destructive confirmation, so under the heading "Remove VISA ****4532" it reads "Pay for your first delivery and your card appears here on its own."',
      fix='Write a real confirmation body.'),
 dict(id='C-5.10', sev='MEDIUM', status='open', cat='Copy',
      title='"Activating in 5s" with a Cancel button, after the alert already fired',
      loc='app/(customer)/sos.tsx:66-69,59-64,157-161',
      detail='sosApi.trigger runs immediately; the countdown and Cancel imply it has not sent. cancelSOS does call sosApi.cancel so the outcome is correct, the copy is not.',
      fix='"SOS sent. Cancel within 5s if this was a mistake."'),
 dict(id='C-5.11', sev='MEDIUM', status='open', cat='Copy',
      title='Hardcoded "Live Tracking Active"',
      loc='app/(customer)/share-trip.tsx:87',
      detail='Rendered unconditionally, including when the screen is opened from the drawer with no delivery at all.',
      fix='Gate on a real delivery.'),
 dict(id='C-5.12', sev='MEDIUM', status='open', cat='Copy',
      title='Emoji and brand casing in RatingModal',
      loc='components/RatingModal.tsx:70,50,53',
      detail='Uses a star emoji for the five rating stars and a folded-hands emoji; every other icon in the app is Ionicons or lucide, and emoji cannot be theme-tinted. Line 53 reads "helps us improve Seirs"; the brand is SEIRS everywhere else.',
      fix='Swap to lucide icons and fix the casing.'),
 # ── unreachable ──────────────────────────────────────────────────────────
 dict(id='C-6.1', sev='MEDIUM', status='open', cat='Unreachable',
      title='fare-breakdown.tsx (373 lines) is unreachable',
      loc='app/(customer)/fare-breakdown.tsx',
      detail='Its only caller is vehicle-select.tsx:460, which runs solely in the !isRide branch. request.tsx always passes mode ride, and send.tsx never touches either screen. The whole screen and the cargo branch feeding it are dead.',
      fix='Delete, or reconnect if the cargo breakdown is wanted.'),
 dict(id='C-6.2', sev='MEDIUM', status='open', cat='Unreachable',
      title='trip-progress.tsx is unreachable',
      loc='app/(customer)/trip-progress.tsx',
      detail='Nothing navigates to it; only comments match. Carries the mock fallbacks in C-2.3, a hardcoded chatId "chat1" at 492, and __DEV__ auto-advance timers at 171-175.',
      fix='Delete.'),
 dict(id='C-6.3', sev='MEDIUM', status='open', cat='Unreachable',
      title='transaction/[id].tsx is unreachable', loc='app/(customer)/transaction/[id].tsx',
      detail='Unreachable, fully mock (C-2.4), dead share button (C-1.8).', fix='Delete.'),
 dict(id='C-6.4', sev='MEDIUM', status='decision', cat='Unreachable',
      title='add-payment.tsx is unreachable but still charges a real N100',
      loc='app/(customer)/add-payment.tsx:18-22,51',
      detail='No screen navigates to it, but it is registered at /add-payment and fully wired to paymentsApi.addCardStart, a real N100 Flutterwave charge. payment-methods.tsx states the flow was deliberately replaced by save-on-first-payment. That contradicts the standing note that the N100 add-card UX shipped and must not change without asking. Line 39 also promises a refund "within 5-10 business days".',
      fix='FOUNDER DECISION: is save-on-first-payment the intended behaviour, and should this screen be deleted?'),
 dict(id='C-6.5', sev='LOW', status='open', cat='Unreachable',
      title='app/modal.tsx is an untouched Expo template',
      loc='app/modal.tsx', detail='Renders "This is a modal". Reachable at /modal and listed in _sitemap.', fix='Delete.'),
 dict(id='C-6.6', sev='MEDIUM', status='open', cat='Unreachable',
      title='components/RatingModal.tsx (135 lines) is exported and never imported',
      loc='components/RatingModal.tsx',
      detail='The live rating flow is app/(customer)/rate/[driverId].tsx. Carries C-1.9 and C-5.12.', fix='Delete.'),
 # ── comments ─────────────────────────────────────────────────────────────
 dict(id='C-7.1', sev='MEDIUM', status='open', cat='Comments',
      title='promo.tsx comment claims the Apply check is validate-only',
      loc='app/(customer)/promo.tsx:44-47',
      detail='Says the live Apply check only validates existence/activity/per-user cap and the discount recalculates at booking. Both halves are false: the backend persists a redemption and increments usageCount, and there is no booking-time re-application. This comment is why C-1.3 looked safe.',
      fix='Correct it when fixing C-1.3.'),
 dict(id='C-7.2', sev='MEDIUM', status='closed', cat='Comments',
      title='send.tsx comment asserted a disproven inset model',
      loc='app/(customer)/send.tsx:2015-2017', detail='Claimed insets.bottom is ~48dp on 3-button Android; measured as 0.',
      fix='Comment rewritten to state the measurement.'),
 dict(id='C-7.3', sev='MEDIUM', status='open', cat='Comments',
      title='payment-methods.tsx describes a CTA that does not exist',
      loc='app/(customer)/payment-methods.tsx:87-89',
      detail='Says the add-payment CTA lives in the body (empty state plus "Add another" at the bottom of the list). No such CTA exists anywhere in the file.', fix='Delete the comment.'),
 dict(id='C-7.4', sev='LOW', status='open', cat='Comments',
      title='heroCards.ts contradicts itself about ctaKey/ctaRoute',
      loc='constants/heroCards.ts:8-10 vs 81-82',
      detail='Lines 8-10 say they render an action button; 81-82 say the article view does not render a sticky CTA. No card sets either field and the article screen never reads them.', fix='Remove the fields or implement them.'),
 dict(id='C-7.5', sev='LOW', status='open', cat='Comments',
      title='Em-dashes in comments (banned project-wide)',
      loc='hooks/use-bookmarks.ts:5,7; hooks/use-rate-card.ts:2,10,18,40,135,273,334,341,361; constants/nigerian-states.ts:5; utils/articleMeta.ts:4,21; i18n/index.ts:45',
      detail='13 occurrences.', fix='Replace with colons, commas or hyphens.'),
 dict(id='C-7.6', sev='LOW', status='open', cat='Comments',
      title='vehicle-select.tsx references a route that does not exist',
      loc='app/(customer)/vehicle-select.tsx:44-45',
      detail='Says cargo mode comes from /multi-stop (the legacy Economy/Premium/Truck list). There is no /multi-stop route and the cargo list is PACKAGE_VEHICLES.', fix='Correct the comment.'),
 dict(id='C-7.7', sev='LOW', status='open', cat='Comments',
      title='Standing TODO markers and ts-ignores',
      loc='constants/rateCard.ts:260,267; app/_layout.tsx:40,42',
      detail='TODO: deprecate; bake into base + perKm. Two @ts-ignore.', fix='Resolve or ticket them.'),
 # ── other ────────────────────────────────────────────────────────────────
 dict(id='C-8.1', sev='MEDIUM', status='open', cat='Other',
      title='Every finished delivery renders a grey badge instead of green',
      loc='app/(customer)/(tabs)/index.tsx:40',
      detail="statusVariant returns success for 'completed', but DeliveryStatus has no 'completed'; the terminal value is 'delivered'.",
      fix="s === 'delivered' || s === 'completed' ? 'success' : ..."),
 dict(id='C-8.2', sev='LOW', status='closed', cat='Other',
      title='activeTrip.unpaid read but absent from the declared type',
      loc='app/(customer)/(tabs)/index.tsx:96-98,197,200',
      detail='A tsc error that worked at runtime.', fix='Added unpaid?: boolean to the trips state type.'),
 dict(id='C-8.3', sev='LOW', status='open', cat='Other',
      title='Unused imports',
      loc='fare-breakdown.tsx:15, vehicle-select.tsx:15 (LAGOS_COORDS); share-trip.tsx:12 (MOCK_USER)',
      detail='', fix='Remove.'),
 dict(id='C-8.4', sev='LOW', status='open', cat='Other',
      title='Dead state and styles',
      loc='sos.tsx:35; vehicle-select.tsx:178,125,515-519; index.tsx:51,30',
      detail='submitting never read; selectedShareable and shared plus five share styles left from the removed toggle; firstName and getGreetingKey unused.', fix='Remove.'),
 dict(id='C-8.5', sev='LOW', status='open', cat='Other',
      title='Dead i18n keys implying features that do not exist',
      loc='i18n/locales/*.json (sos block and others)',
      detail='Nine in sos alone (tapToActivate, holdToCancel, callPolice, callTrustedContact, shareLocation, iAmSafe, iAmSafeConfirm, sosSent, sosSentMsg) implying "I am Safe" and "Trusted Contact" features that do not exist; plus liveChatComingSoon, verifyIdentityComingSoon, profile.walletSub, profile.myTrips, notifications.walletTopupSub.',
      fix='Delete the keys or build the features.'),
 # ── device-found (not in the audit) ──────────────────────────────────────
 dict(id='C-D1', sev='HIGH', status='closed', cat='Found on device', device=True,
      title='Keke, Small Truck and Large Truck could not be booked at all',
      loc='shared/services/api.ts pricingApi.quote',
      detail='The Send screen holds the UI alias (keke, truck_sm, truck_lg) as its vehicle id and pricingApi.quote passed it straight through, so the engine answered "Unknown vehicle type: keke". Booking refuses without a server quote, so tapping Pay after the full four-step flow surfaced the raw backend error. deliveriesApi.quote/create normalised aliases all along; the pricing call never did.',
      fix='pricingApi.quote now runs normalizeBodyVehicle. Verified end to end: SRS-QS335M4Q booked at N2,589.'),
 dict(id='C-D2', sev='HIGH', status='closed', cat='Found on device', device=True,
      title='The review showed a price the server does not charge',
      loc='app/(customer)/send.tsx quote fallback',
      detail='The failed quote was caught silently and the screen fell back to the bundled client formula, which prices the service fee as an 18% PERCENTAGE while the live card charges a FLAT amount, currently 0. Review read N2,650 where the engine returns N2,588.96.',
      fix='Fixed by C-D1: the server quote now lands, so the review shows N2,589 and the phantom N376 service-fee row is gone.'),
 dict(id='C-D3', sev='HIGH', status='closed', cat='Found on device', device=True,
      title='A real fee was charged and never shown',
      loc='app/(customer)/send.tsx Order Summary',
      detail='Declaring a package value above the card threshold adds a premium (N500 at N150,000, N24,750 at N5,000,000, verified against the live engine) folded silently into the total. The summary own comment already called a hidden non-zero fee a lie.',
      fix='Added a High-value cover line, rendered only when the engine charges one.'),
 dict(id='C-D4', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='The Pay button sat dead with no reason given',
      loc='app/(customer)/send.tsx CTA bar',
      detail='The consent checkbox is the last element on a long review, so landing at the top you see a greyed-out "Pay N2,589" and nothing explaining it.',
      fix='A hint above the CTA names the blocker and taps through to the checkbox.'),
 dict(id='C-D5', sev='HIGH', status='closed', cat='Found on device', device=True,
      title='The "Features" tab rendered the customer own cancelled bookings',
      loc='app/(customer)/(tabs)/index.tsx:136',
      detail='TRIPS.slice(0, 2) grabbed the two most recent bookings whatever their state. On the founder phone it showed two cancelled QA rows under a tab promising features. Cancelled bookings had no home anywhere else in the app.',
      fix='The tab is now Cancelled and filters on that status.'),
 dict(id='C-D6', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='Home trip cards printed kobo and gave rides a truck icon',
      loc='app/(customer)/(tabs)/index.tsx:363,376',
      detail='N4,676.25 instead of N4,676; every row used the delivery-truck icon including rides.',
      fix='Math.round on the price and a car icon when kind is ride.'),
 dict(id='C-D7', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='Empty states were raw English strings in a four-language app',
      loc='app/(customer)/(tabs)/index.tsx:342-347',
      detail='Hardcoded English while everything around them used t().',
      fix='Six keys added across en, ha, ig and yo.'),
 dict(id='C-D8', sev='MEDIUM', status='closed', cat='Found on device', device=True,
      title='The unpaid state used a colour that is not in the SEIRS palette',
      loc='trip/[id].tsx, track.tsx, (tabs)/index.tsx',
      detail='Founder caught this on the phone: generic Tailwind amber (#F59E0B / #D97706) appears nowhere in the brand palette.',
      fix='Brand yellow #FFBE0B with navy text for contrast, unpaid state only. Genuine warnings stay amber.'),
 dict(id='C-D9', sev='MEDIUM', status='open', cat='Found on device', device=True,
      title='The cargo vehicle step shows no prices',
      loc='app/(customer)/send.tsx step 3',
      detail='The ride flow shows a live price per vehicle; the package flow shows only capacity, so a sender picks Okada vs Car vs Danfo blind until the review screen.',
      fix='FOUNDER DECISION: build per-vehicle pricing on the cargo step to match the ride flow?'),
 dict(id='C-D10', sev='MEDIUM', status='decision', cat='Found on device', device=True,
      title='The home hero gradient is nearly invisible in dark mode',
      loc='components/HomeHeroAnimated.tsx:94-95',
      detail='skyTop #1C2128 to skyBottom #0D1117 against a near-black page, so the top of the card has no visible boundary and the hero reads as half-painted. Fine in light mode.',
      fix='FOUNDER DECISION: lift the dark-mode gradient or give the card a border.'),
 dict(id='C-D11', sev='LOW', status='decision', cat='Found on device', device=True,
      title='The empty-state illustration is a bright white disc on a near-black screen',
      loc='components/Illustration.tsx usage on home',
      detail='A light-mode asset dropped into the dark theme unchanged; it dominates the screen.',
      fix='FOUNDER DECISION: make the illustration theme-aware.'),
]
