# -*- coding: utf-8 -*-
"""Driver app findings."""
APP = 'Driver app'
KEY = 'driver'
FINDINGS = [
 # ── dead controls ────────────────────────────────────────────────────────
 dict(id='D-1.1', sev='HIGH', status='open', cat='Dead controls',
      title='Job Details can never load. Every "Available Jobs" tap is a dead end',
      loc='app/(driver)/job/[id].tsx:45',
      detail='Calls deliveriesApi.get(id) which is GET /deliveries/:id. The backend findOne filters where customer.id = userId, so a driver always 404s, the catch sets job null, and the screen renders "Job not found / Go Back". Reached from the ACTIVE JOB card and every pending job card. There is exactly one @Get(":id") and no driver branch.',
      fix='Add a driver branch to findByIdForUser (OR driver.user.id = userId), or point the screen at the available-jobs data already in hand.'),
 dict(id='D-1.2', sev='HIGH', status='open', cat='Dead controls',
      title='The main trip screen always shows "Delivery not found"',
      loc='app/(driver)/active.tsx:86',
      detail='deliveriesApi.track(id) is GET /deliveries/track/:code and findByTracking matches on trackingCode only. id here is the delivery UUID passed from job/[id].tsx:142, which can never equal an SRS- code. From notifications.tsx:163 it arrives with no id at all.',
      fix='Use driversApi.getDelivery(id) once D-1.3 is fixed, or pass trackingCode from the caller.'),
 dict(id='D-1.3', sev='HIGH', status='open', cat='Dead controls',
      title='The whole multi-stop flow 403s for drivers',
      loc='app/(driver)/delivery/[id].tsx:100,171,185 and multi-leg.tsx:154',
      detail='getDelivery / markStopArrived / markStopDelivered hit business/deliveries/... and all three routes carry @UseGuards(BusinessAccountGuard), which throws unless req.user.businessAccountId is set. A driver has none. Even past the guard, business.service.ts:533 compares the wrong ids: delivery.driver?.id === userId is a driver row id against a USER id, never true.',
      fix='Drop BusinessAccountGuard from the three stop/detail routes and change the check to delivery.driver?.user?.id === userId.'),
 dict(id='D-1.4', sev='HIGH', status='open', cat='Dead controls',
      title='A job notification lands on a dead screen',
      loc='app/(driver)/notifications.tsx:163',
      detail='n.deliveryId is checked but never passed, so active.tsx receives id undefined.',
      fix='router.push({ pathname: "/(driver)/active", params: { id: n.deliveryId } }).'),
 dict(id='D-1.5', sev='HIGH', status='open', cat='Dead controls',
      title='"Decline" is a confirm dialog that sends nothing',
      loc='app/(driver)/job/[id].tsx:157-179',
      detail='The dialog says "This job will be offered to another driver" but for a non-Travel-Buddy job the handler is just router.back(). The 45-second countdown labelled "Accept in {n}s or it auto-declines" also only calls router.back(). There is no generic decline endpoint. Dispatch never learns the driver said no.',
      fix='Add POST /deliveries/:id/decline and call it, or change the copy to "Skip for now" and stop promising re-offer.'),
 dict(id='D-1.6', sev='HIGH', status='open', cat='Dead controls',
      title='The anti-theft trunk photo is uploaded and thrown away',
      loc='app/(driver)/trunk-check.tsx:44-53',
      detail='The uploaded URL is only console.logged, while the footnote at 120 tells the driver "Photos here become evidence in any dispute". It is evidence of nothing.',
      fix='Attach the URL to the delivery before the success alert, and drop the console.log.'),
 dict(id='D-1.7', sev='MEDIUM', status='open', cat='Dead controls',
      title='"Report a Trip Issue" has no onPress',
      loc='app/(driver)/help.tsx:153',
      detail='Full-width red card with a chevron for "Customer dispute, route issue, vehicle damage". Tapping does nothing.',
      fix='router.push("/(driver)/support/new").'),
 dict(id='D-1.8', sev='MEDIUM', status='open', cat='Dead controls',
      title='"Clear Trip History Cache" has no onPress',
      loc='app/(driver)/privacy.tsx:194', detail='Chevron and all.', fix='Wire to AsyncStorage.removeItem or delete the row.'),
 dict(id='D-1.9', sev='MEDIUM', status='open', cat='Dead controls',
      title='"Availability Hours" never reaches the server',
      loc='app/(driver)/schedule.tsx:88-94',
      detail='handleSave writes only to AsyncStorage; matching has no idea. The screen presents a Save button and a "Saved!" state.',
      fix='POST the schedule to the driver record, or relabel it "Personal reminder (this device only)".'),
 dict(id='D-1.10', sev='MEDIUM', status='open', cat='Dead controls',
      title='The "30-minute reminders" switch is pure local state',
      loc='app/(driver)/schedule.tsx:66,175-180', detail='Never persisted, never read, and no such push exists.', fix='Remove or build it.'),
 dict(id='D-1.11', sev='MEDIUM', status='open', cat='Dead controls',
      title='The acceptance-rate gate is inert',
      loc='app/(driver)/last-order.tsx:37,44,157',
      detail='drivers.service.ts hardcodes todayAcceptanceRate: null with the comment "Acceptance-rate calc is a follow-up". The card always shows a dash, meetsThreshold is always true, and the copy "Last Order requires 80%" describes a rule nothing enforces.',
      fix='Compute the rate or change the copy.'),
 dict(id='D-1.12', sev='MEDIUM', status='open', cat='Dead controls',
      title='A hardcoded green "Online" under the other party name',
      loc='app/(driver)/messages/[chatId].tsx:166', detail='No presence data is fetched; it is always shown.', fix='Remove or wire real presence.'),
 dict(id='D-1.13', sev='LOW', status='open', cat='Dead controls',
      title='Double Pressable on the notification bell',
      loc='components/NotificationBell.tsx:24, (tabs)/index.tsx:241',
      detail='The bell is itself a Pressable but is wrapped in another with a duplicate router.push. The outer handler never fires.', fix='Unwrap.'),
 dict(id='D-1.14', sev='LOW', status='open', cat='Dead controls',
      title='"Remind me" Pressable with no onPress',
      loc='app/(driver)/schedule.tsx:154', detail='Inside the always-empty PREBOOKED list, so unreachable.', fix='Remove.'),
 # ── mock data ────────────────────────────────────────────────────────────
 dict(id='D-2.1', sev='HIGH', status='closed', cat='Mock data',
      title='A fabricated ETA displayed as fact on every pool leg',
      loc='app/(driver)/multi-leg.tsx:56,60,95',
      detail='etaMinutes: 8 for every leg, summed into a pool total, so a 3-leg pool always read "24m".',
      fix='Replaced with real distanceKm from the delivery and a total-distance badge. Invented minutes are exactly what this platform does not promise.'),
 dict(id='D-2.2', sev='MEDIUM', status='closed', cat='Mock data',
      title='A human passenger was always labelled "Package"',
      loc='app/(driver)/multi-leg.tsx:52',
      detail='type: (d.packageDescription ? "package" : "package") is a tautology, making the Users icon and the "Passenger" label at 112/125 dead code.',
      fix="type: d.kind === 'ride' ? 'passenger' : 'package'."),
 dict(id='D-2.3', sev='MEDIUM', status='open', cat='Mock data',
      title='A fully-wired paywall for a program the founder paused',
      loc='app/(driver)/subscription.tsx',
      detail='profile.tsx:81 says SEIRS Premium was removed because the program is paused platform-wide, and deliveries.service.ts:1349 hardcodes driverIsPro false. The screen still offers "Activate: N5,000/week" charged from a wallet, which the no-wallet direction retires. Only reachable by deep link.',
      fix='Delete the screen or gate it behind a live flag.'),
 dict(id='D-2.4', sev='MEDIUM', status='open', cat='Mock data',
      title='The pool cap of 4 is hardcoded in two files',
      loc='app/(driver)/(tabs)/index.tsx:305, multi-leg.tsx:68,86',
      detail='{activeJobs.length}/4 and 4 - slotsUsed, rather than a Fee Catalogue row.', fix='Read from the catalogue with a code fallback.'),
 dict(id='D-2.5', sev='LOW', status='open', cat='Mock data',
      title='243 lines of fake drivers, jobs, earnings, ratings, banks and chats',
      loc='constants/driverMockData.ts',
      detail='Only DRIVER_HELP_FAQS is imported. Nothing else references MOCK_DRIVER*, NIGERIAN_BANKS or WEEKLY_EARNINGS. A loaded gun sitting in the repo.',
      fix='Move DRIVER_HELP_FAQS into help.tsx and delete the file.'),
 # ── money ────────────────────────────────────────────────────────────────
 dict(id='D-4.1', sev='HIGH', status='open', cat='Money',
      title='"This Week" and "Today" are computed client-side from a server-capped list',
      loc='app/(driver)/(tabs)/earnings.tsx:77-97',
      detail='getHistory is limit 50. A driver who completes more than 50 trips in a week sees an UNDERSTATED week total, and the bar chart under-reports with it. Meanwhile EarningsDashboard already carries today.earned and week.earned computed server-side over the full table. todayTotal is also a rolling 24h bucket, not calendar-today like the server.',
      fix='Read dashboard.week.earned and dashboard.today.earned; keep history only for the chart shape.'),
 dict(id='D-4.2', sev='MEDIUM', status='open', cat='Money',
      title='Two different "this month" on the same screen',
      loc='app/(driver)/(tabs)/earnings.tsx:143 vs :109',
      detail='The Month tab shows dashboard.month.earned (server, full table); EarningsCalendar renders "N X this month" summed client-side from the same 50-row history. They disagree for any busy driver.',
      fix='Pass dashboard.month.earned into the calendar header.'),
 dict(id='D-4.3', sev='MEDIUM', status='open', cat='Money',
      title='Two sources for "Today" across the app',
      loc='app/(driver)/(tabs)/index.tsx:416 vs the Earnings tab',
      detail='The home widget shows driverData.todayEarnings, summed from delivery.driverEarnings for DELIVERED rows. The Earnings tab sums driver_earning.driverNet from the ledger. Different numbers: the delivery column is the booked share, the ledger row derives from what the customer actually paid, and a delivered-but-unreleased delivery counts on home with no ledger row at all.',
      fix='The home widget already fetches the dashboard for withdrawable; read d.today.earned from the same response.'),
 dict(id='D-4.4', sev='MEDIUM', status='open', cat='Money',
      title='The minimum withdrawal is hardcoded',
      loc='app/(driver)/withdrawal.tsx:27',
      detail='MIN_WITHDRAWAL = 1000 while the server reads driver_min_payout_ngn from the Fee Catalogue. If an admin changes it the client gate silently disagrees. Same for the daily caps, which the app never surfaces, so a new driver requesting N60,000 only finds out via a server rejection.',
      fix='Add minPayoutNgn and the caps to /earnings/dashboard and read them.'),
 dict(id='D-4.5', sev='MEDIUM', status='open', cat='Money',
      title='"After 30% Seirs commission" is hardcoded copy',
      loc='app/(driver)/job/[id].tsx:218',
      detail='The real cut is PLATFORM_COMMISSION in common/constants/pricing.ts, and the per-trip rows already show the exact fee. Goes stale the day the rate moves.',
      fix='Render from the constant or drop the sentence.'),
 dict(id='D-4.6', sev='MEDIUM', status='open', cat='Money',
      title='Transaction detail loads the whole history and finds by id client-side',
      loc='app/(driver)/transaction/[id].tsx:32-33,60,94',
      detail='Any entry older than the last 50 renders "Transaction not found". isCredit = true is a constant, making the ternary at 94 a dead branch.',
      fix='Fetch the single earning by id.'),
 # ── keyboard / layout ────────────────────────────────────────────────────
 dict(id='D-5.1', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='Bottom CTA bars double-count insets.bottom',
      loc='withdrawal.tsx:325, add-bank.tsx:259, vehicle.tsx:298',
      detail='SafeAreaView already pads edges bottom, then the bar adds Spacing.md + insets.bottom again. With edgeToEdgeEnabled the button floats ~112dp above the screen edge on the 3-button nav.',
      fix="Drop 'bottom' from the SafeAreaView edges on those three screens."),
 dict(id='D-5.2', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='Departure date/time is free text with no keyboard type',
      loc='app/(driver)/interstate.tsx:189-196',
      detail='Placeholder YYYY-MM-DD HH:mm, no keyboardType, no date picker; a wrong format is rejected only after tapping Declare. This is the one field a driver fills at a bus park.',
      fix='keyboardType="numbers-and-punctuation" as a stopgap, a real date picker properly.'),
 dict(id='D-5.3', sev='MEDIUM', status='open', cat='Keyboard and layout',
      title='The weekly-goal modal has no keyboard avoidance',
      loc='app/(driver)/(tabs)/earnings.tsx:217-246',
      detail='autoFocus opens the keyboard immediately and the Save/Cancel row sits below the input; on Android the buttons can be covered.',
      fix='Wrap in KeyboardAvoidingView or lift the row.'),
 # ── copy ─────────────────────────────────────────────────────────────────
 dict(id='D-6.1', sev='HIGH', status='closed', cat='Copy',
      title='The driver SOS screen was unreadable in light mode',
      loc='app/(driver)/sos.tsx:114 and all text styles',
      detail='Page background isDark ? #0A0000 : #FFF1F1 while headerTitle, idleTitle, idleDesc, activeDesc, cancelBtnText, emergencyLabel and emergencySectionTitle are all hardcoded white. On the near-white pink everything except two red strings vanished. This is the safety screen.',
      fix='Deep red ground in both themes, matching the customer fix.'),
 dict(id='D-6.2', sev='MEDIUM', status='open', cat='Copy',
      title='Banned em-dash, on screen',
      loc='app/(driver)/(tabs)/index.tsx:414',
      detail="withdrawable == null ? '-' uses an em-dash character. Second occurrence in a comment at components/CorridorCard.tsx:2.",
      fix="Plain hyphen."),
 dict(id='D-6.3', sev='MEDIUM', status='open', cat='Copy',
      title='Non-Nigerian vehicle vocabulary on the first screen a driver sees',
      loc='app/(auth)/driver-register.tsx:27,30',
      detail="Registration says 'Motorcycle' and 'Van'; app/(driver)/vehicle.tsx says 'Okada (Motorcycle)' and 'Van / Danfo'. Same app, two vocabularies.",
      fix='Copy the labels from vehicle.tsx.'),
 dict(id='D-6.4', sev='MEDIUM', status='open', cat='Copy',
      title='The offline story is fiction',
      loc='app/(driver)/status-broadcast.tsx:50,71,110',
      detail='Promises "your message is queued locally and delivered the moment your connection comes back", "will retry until acknowledged", and location "logged offline every 30s, uploaded in batches". There is no queue: send() is a bare await in a try/catch that alerts on failure. offlineSyncApi is exported and imported by nothing; there is no NetInfo dependency and no AsyncStorage queue anywhere. This is exactly the copy a driver relies on when they lose signal in traffic.',
      fix='Build the queue or delete the promise.'),
 dict(id='D-6.5', sev='MEDIUM', status='open', cat='Copy',
      title='"Re-enabling within 30 minutes counts against next-day priority"',
      loc='app/(driver)/last-order.tsx:173',
      detail='No such logic exists, and it contradicts the bullet directly above it and the handler at 79.', fix='Delete the line.'),
 dict(id='D-6.6', sev='MEDIUM', status='open', cat='Copy',
      title='The SOS countdown lies',
      loc='app/(driver)/sos.tsx:81 vs :143',
      detail='fireSOS POSTs immediately, then shows "SOS in 5s..." with a Cancel button. Ops is already alerted. The cancel is a real un-send so the mechanism is fine; the wording is not.',
      fix='"SOS sent. Cancel within 5s if this was a mistake."'),
 dict(id='D-6.7', sev='MEDIUM', status='open', cat='Copy',
      title='"Payment will be credited to your wallet shortly"',
      loc='app/(driver)/active.tsx:389',
      detail='Earnings clear in 2 business days, which every other screen states correctly. "Shortly" is a promise the ledger does not keep, and "wallet" is the retired model.',
      fix='State the real clearance.'),
 dict(id='D-6.8', sev='MEDIUM', status='open', cat='Copy',
      title='A ride is presented to the driver as a package',
      loc='app/(driver)/active.tsx:576,729',
      detail='The banner switches to RIDE_STEPS, but the info card is still titled "Package Details" with Size/Fragile rows, and the Progress list is hardcoded to STATUS_STEPS, so a ride driver reads "Package Collected".',
      fix="Gate the Package Details card on kind !== 'ride' and use the same stepConfig for the progress list."),
 dict(id='D-6.9', sev='MEDIUM', status='open', cat='Copy',
      title='"You can decline any individual offer"',
      loc='app/(driver)/interstate.tsx:303', detail='Per D-1.5, declining a non-Travel-Buddy offer sends nothing.', fix='Fix D-1.5 or change the copy.'),
 dict(id='D-6.10', sev='MEDIUM', status='open', cat='Copy',
      title='The packages toggle ON/OFF colour is bound to the wrong state',
      loc='app/(driver)/interstate.tsx:226',
      detail='Turning packages off while passengers is on leaves the "OFF" text in primary colour. Copy-paste from the row below.',
      fix='Bind to takePackages alone.'),
 dict(id='D-6.11', sev='LOW', status='open', cat='Copy',
      title='Support email disagrees with the rest of the platform',
      loc='app/(driver)/privacy.tsx:86', detail='Says support@seirs.co; everywhere else is seirs.app.', fix='Pick one.'),
 dict(id='D-6.12', sev='LOW', status='open', cat='Copy',
      title='Offers a bonus program the founder deferred',
      loc='app/(driver)/privacy.tsx:93',
      detail='"Personalised Offers / bonus offers tailored to your driving patterns" while the bonus program is on the pending-decisions list.', fix='Remove until it ships.'),
 dict(id='D-6.13', sev='LOW', status='decision', cat='Copy',
      title='199 is labelled "Police"',
      loc='app/(driver)/sos.tsx:21', detail='In Nigeria 199 is commonly the Fire Service and 112 is the national emergency line.',
      fix='FOUNDER DECISION: confirm the number set (same question as C-5.8).'),
 dict(id='D-6.14', sev='LOW', status='open', cat='Copy',
      title='Every review avatar initial is the letter T',
      loc='app/(driver)/ratings.tsx:51,136', detail="Sets customer: 'Trip SEIRS-XXXX'.", fix='Use the real first name.'),
 # ── privacy ──────────────────────────────────────────────────────────────
 dict(id='D-7.1', sev='HIGH', status='closed', cat='Passenger privacy',
      title='Full legal name AND phone number shown to the driver on rides',
      loc='app/(driver)/active.tsx:598-620',
      detail='The Customer card was not gated on kind, so it rendered customer.name and customer.phone directly above the correctly-built Passenger card (first name, chat only). Rendered in addition to, not instead of.',
      fix="Gated on (delivery as any).kind !== 'ride'."),
 dict(id='D-7.2', sev='HIGH', status='closed', cat='Passenger privacy',
      title='The passenger surname, on the ride path specifically',
      loc='app/(driver)/delivery/[id].tsx:246', detail='Joined receiverFirstName and receiverLastName into the RIDE header.',
      fix='Dropped receiverLastName. The surname is the lookup key the rule exists to withhold.'),
 dict(id='D-7.3', sev='HIGH', status='closed', cat='Passenger privacy',
      title='Full name on the ACTIVE JOB card',
      loc='app/(driver)/(tabs)/index.tsx:329',
      detail='The job list below it correctly masks rides; the active card was missed.', fix='First name only when kind is ride.'),
 dict(id='D-7.4', sev='HIGH', status='closed', cat='Passenger privacy',
      title='Full customer name in trip history and pool legs',
      loc='app/(driver)/(tabs)/history.tsx:48,155 and multi-leg.tsx:57,148',
      detail='Both mapped straight from d.customer.name, both including rides; multi-leg renders it as "For: <full name>".', fix='First name only when kind is ride.'),
 dict(id='D-7.5', sev='HIGH', status='closed', cat='Passenger privacy',
      title='Full name in the chat inbox, propagating into the thread header and every avatar',
      loc='shared/components/chat/MessagesInbox.tsx:203,219',
      detail='The name is also carried into the chat screen header and every incoming bubble. active.tsx does this correctly; the inbox path was the leak. Note the inbox is SHARED, so truncating client-side would wrongly hide the DRIVER name from customers.',
      fix='Fixed at the source: chat.service.ts now sends the driver a first name only.'),
 dict(id='D-7.6', sev='HIGH', status='closed', cat='Passenger privacy',
      title='The backend handed the driver the entire user row',
      loc='seirs-backend/src/deliveries/deliveries.service.ts findActiveByDriverUserId',
      detail='leftJoinAndSelect on d.customer returned the full User entity with name, email and phone all selected by default. The available-jobs feed was sanitised in a 2026-08-10 audit; the ACTIVE-job feed never was.',
      fix='redactCustomerForDriver: rides get first name only, no surname, no phone, no email; packages keep the sender phone so a courier can reach the door. Admin payloads untouched.'),
 # ── unreachable ──────────────────────────────────────────────────────────
 dict(id='D-8.1', sev='MEDIUM', status='open', cat='Unreachable',
      title='subscription.tsx (257 lines) is genuinely orphaned',
      loc='app/(driver)/subscription.tsx', detail='No drawer entry, no profile row, no router.push anywhere. See D-2.3.', fix='Delete.'),
 # ── comments ─────────────────────────────────────────────────────────────
 dict(id='D-9.1', sev='LOW', status='open', cat='Comments',
      title='Five stale comments describing behaviour the code no longer has',
      loc='last-order.tsx:18-21; status-broadcast.tsx:15-18; scan-package.tsx:16-17; multi-leg.tsx:15-17; components/EarningsCalendar.tsx:4-5',
      detail='Each says backend wiring is "planned" or "comes later" when the real call is already made; multi-leg promises a mark-complete control that does not exist; EarningsCalendar claims arrows scroll back indefinitely when it only aggregates 50 rows.',
      fix='Rewrite or delete.'),
 dict(id='D-9.2', sev='MEDIUM', status='open', cat='Comments',
      title='Standing TODO: stop deliveries complete with no proof of delivery',
      loc='app/(driver)/delivery/[id].tsx:182',
      detail='"TODO Phase 5b: tie into proof-of-delivery photo + signature. For now we ship the action without proof."', fix='Build the proof step.'),
 dict(id='D-9.3', sev='LOW', status='open', cat='Comments',
      title='Dead code and unused styles',
      loc='earnings.tsx:375-376; (tabs)/index.tsx:525,563,569-571,182,33; active.tsx:903-904; history.tsx:45,158,168',
      detail='tierChip leftovers from the removed tier badge; headerGreet/heatmapWidget/goalTrack/goalFill/heatmapBox; weekEarnings computed never rendered; avatar styles superseded by the component; history maps distance but reads item.distanceKm so distance never renders, and reads item.rating which the mapper never sets, making the whole rating block dead.',
      fix='Remove.'),
 # ── other ────────────────────────────────────────────────────────────────
 dict(id='D-10.1', sev='HIGH', status='open', cat='Other',
      title='"My Trips" can never show a completed trip and always reads "N0 earned"',
      loc='app/(driver)/(tabs)/history.tsx:38,84',
      detail='Calls GET /deliveries/driver which filters to ASSIGNED | PICKED_UP | IN_TRANSIT only, so the Delivered and Cancelled tabs are permanently empty and the header badge sums nothing. If the filter is ever loosened it would instead sum money the driver has not yet earned.',
      fix='Add a status/history endpoint for the driver, or reuse earningsApi.history() which is already paid-trip data.'),
 dict(id='D-10.2', sev='HIGH', status='open', cat='Other',
      title='The KYC screen never loads existing documents',
      loc='app/(driver)/kyc.tsx:63,72',
      detail='docs initialises from INITIAL_DOCS (all eight not_uploaded) and the only effect probes camera permission. setDocs is called only after a fresh upload. An approved driver reopening KYC sees 0% progress and eight "Not Uploaded" rows, and will re-upload everything. The data is right there: /drivers/me spreads the whole entity and the driver entity holds all eight *Url columns.',
      fix='One effect that calls driversApi.me() and marks each doc uploaded where its column is non-null.'),
 dict(id='D-10.3', sev='HIGH', status='open', cat='Other',
      title='The phone number is submitted raw, not normalised',
      loc='app/(auth)/driver-register.tsx:96',
      detail='normalisePhone is used for VALIDATION but the payload sends the raw field. A driver typing +2348012345678 passes validation and is registered with phone "+234+2348012345678"; typing 0801 234 5678 registers "+234801 234 5678". The placeholder invites both formats.',
      fix="phone: '+234' + normalisePhone(phone).replace(/^0/, '')."),
 dict(id='D-10.4', sev='MEDIUM', status='open', cat='Other',
      title='The bar chart mislabels every day except Sunday',
      loc='app/(driver)/(tabs)/earnings.tsx:27',
      detail="DAY_LABELS is a fixed Mon..Sat run plus 'Today', but dayTotals is a ROLLING 7-day window. On a Wednesday, 'Sat' is Tuesday money and 'Mon' is last Thursday. Only correct if today is Sunday.",
      fix='Derive the labels from the actual dates.'),
 dict(id='D-10.5', sev='MEDIUM', status='open', cat='Other',
      title='NaN the moment the fetch is fixed',
      loc='app/(driver)/active.tsx:582-583',
      detail='The tracking payload returns no distanceKm, driverEarnings, packageDescription, isFragile, receiverFirstName or customer, yet the screen reads all of them: "NaN km" and "N NaN". isFragile absent also means a fragile package always renders "Fragile: No". Currently masked by D-1.2.',
      fix='Fix D-1.2 first, then read from the right payload.'),
 dict(id='D-10.6', sev='LOW', status='open', cat='Other',
      title='The location interval outlives the screen',
      loc='app/(driver)/(tabs)/index.tsx:132-146',
      detail='startLocationUpdates sets a 15s interval posting GPS with no useEffect cleanup, and stopLocationUpdates never nulls the ref. After logout the timer keeps firing updateLocation.',
      fix='Clear it on unmount, as active.tsx already does.'),
 dict(id='D-10.7', sev='LOW', status='open', cat='Other',
      title='Two divergent phone validators',
      loc='driver-register.tsx:38 vs edit-profile.tsx:29',
      detail='Registration allows only 070|071|080|081|090|091; edit allows any 0[789]. A prefix the NCC issues tomorrow is editable but not registerable.', fix='Share one validator.'),
 dict(id='D-10.8', sev='LOW', status='open', cat='Other',
      title='Split names are never populated at signup',
      loc='app/(auth)/driver-register.tsx:89',
      detail='Joins first/middle/last into a single name because authApi.register has no firstName/lastName. Since the ride-privacy rule and profile.tsx both prefer user.firstName, every driver runs on the string-split fallback until they open Edit Profile.',
      fix='Add the fields to register.'),
 dict(id='D-D1', sev='LOW', status='closed', cat='Found on device', device=True,
      title='Duplicate style keys silently dropped six styles',
      loc='app/(driver)/seirs-id.tsx:166-182',
      detail='howCard, howTitle, howRow, howStep, howStepText and howText were each defined twice in one StyleSheet; the second block won and the first was dead. Surfaced by running the app own typecheck, which had never been run.',
      fix='Removed the dead first block, preserving the rendered appearance exactly.'),
]
