# -*- coding: utf-8 -*-
"""Public website findings (includes the shared/platform items)."""
APP = 'Website and platform'
KEY = 'website'
FINDINGS = [
 dict(id='W-1', sev='HIGH', status='closed', cat='Broken links',
      title='/dispute-resolution does not exist, linked from two apps legal menus',
      loc='customer-app privacy.tsx:246, driver-app privacy.tsx:99',
      detail='Both open https://seirs.app/dispute-resolution. No such route exists on the site, so a user tapping "Dispute Resolution" from a legal menu gets the 404 page.',
      fix='Both repointed at /terms-of-service, which carries the disputes section.'),
 dict(id='W-2', sev='HIGH', status='closed', cat='Broken links',
      title='/terms does not exist, linked from the customer profile menu',
      loc='customer-app (tabs)/profile.tsx:123',
      detail='The real route is /terms-of-service. The .catch fallback does not save it: openURL resolves once the browser opens, so the user sees a 404 rather than the coming-soon alert.',
      fix='Repointed to /terms-of-service.'),
 dict(id='W-3', sev='HIGH', status='open', cat='Broken links',
      title='Referral links 404 for every user who shares one',
      loc='customer-app referral.tsx:20',
      detail="WEB_REFERRAL_BASE is 'https://seirs.app/r/'. No src/app/r/ route exists. The referral system is otherwise fully wired, so the landing page is the only missing piece.",
      fix='Add src/app/r/[code]/page.tsx that stores the code and forwards to the store link.'),
 dict(id='W-4', sev='HIGH', status='open', cat='Configuration',
      title='Five different names for "the website URL", with conflicting defaults',
      loc='launch.ts:78, sitemap.ts:9, deliveries.service.ts:1941, payments.service.ts:527, mail.service.ts:215, statements.service.ts:32, plus ~20 hardcoded literals',
      detail='NEXT_PUBLIC_SITE_URL and PUBLIC_SITE_URL default to seirs.app; WEBSITE_URL and PUBLIC_WEB_URL default to seirs-website.vercel.app. The two halves already disagree in production: a WhatsApp collect link goes to seirs.app/collect while the password-reset email from the same backend goes to vercel.app/reset-password. The LAUNCH_CHECKLIST claims setting one Vercel env var resolves the split; it resolves one of five. Highest-stakes consequences: the public tracking flow and the collect-fee flow both sit on the unresolved host.',
      fix='Settle the domain, then export one shared constant that all three apps and the backend import. Rewrite the checklist entry to name all five plus the literals.'),
 dict(id='W-5', sev='HIGH', status='closed', cat='False claims',
      title='"NDPR compliant" was still rendered, under a comment saying it was removed',
      loc='src/app/page.tsx:855-859,831-845',
      detail='A 15-line comment above the array explained the badge was removed because NITDA NDPR registration is not started and "that is the kind of unearned compliance claim a regulator acts on". The removal was written and never applied, so it asserted a registration that does not exist on every homepage view. The same comment said "The four below" while the array held three.',
      fix='Deleted the entry and corrected the comment, which now also records that the removal was written and never applied.'),
 dict(id='W-6', sev='HIGH', status='decision', cat='Legal',
      title='The Terms prohibit two things the homepage advertises as real services',
      loc='terms-of-service/page.tsx:191,193 vs page.tsx:547,552',
      detail='Terms strictly prohibit "Live animals" and "Perishable items without prior arrangement". The homepage sells "Live animals: yes, even the Christmas chicken" and "Hot food: amala that arrives still steaming", and states of those tiles that "every one of them is a real option in the app, priced on its own rate card". The backend confirms it: live_animals and food_hot are live category codes the engine prices, and both appear in the customer app category picker. A customer whose live-animal delivery goes wrong is met with a clause saying it was never allowed.',
      fix='FOUNDER DECISION: carve both out of section 4 with the conditions that actually apply, or remove the categories.'),
 dict(id='W-7', sev='HIGH', status='closed', cat='False claims',
      title='"Night pickups carry a night fee that goes to you in full"',
      loc='for-drivers/page.tsx:166',
      detail='The seeded rate card sets night driverSharePercent to 80, and the engine multiplies by that share. The driver gets 80%, not 100%. The homepage comment had it right; this recruitment page did not.',
      fix='Changed to "Night pickups carry a night fee, and most of it is yours", with the card field named in a comment.'),
 dict(id='W-8', sev='HIGH', status='decision', cat='Legal',
      title='The Terms create a prepaid customer-funds balance',
      loc='terms-of-service/page.tsx:153-154,222,362-363 plus layout.tsx, page.tsx and all five for-* pages',
      detail='"Business wallet funds are non-refundable except as stated", "Business wallet top-ups are processed immediately", "Outstanding wallet balances will be refunded to a verified Nigerian bank account within 14 business days". This is deposit-taking language in a binding document and it contradicts the no-business-wallet rule. The backend DOES implement it (business-account walletBalance, business-wallet-tx), so it is a live policy conflict, not a copy error. The existing LEGAL_AUDIT_REPORT flags the same thing.',
      fix='FOUNDER DECISION. This is the single largest legal exposure on the site and should be settled before launch, not at launch.'),
 dict(id='W-9', sev='HIGH', status='decision', cat='False claims',
      title='Price-finality claim contradicted by the Terms and by the product',
      loc='how-it-works/page.tsx:163 vs terms-of-service/page.tsx:209',
      detail='"The price you see is the price you pay. No surcharges at the end." The Terms say prices at order creation are estimates and may vary. The product also sells partner-store storage fees, redirection fees and counter fees. A consumer-protection challenge writes itself.',
      fix='FOUNDER DECISION: recommend "The quote is locked when you book", which the backend quote pin actually does, and dropping the no-surcharges line.'),
 dict(id='W-10', sev='HIGH', status='open', cat='False claims',
      title='The contact page claims live operations in four cities',
      loc='contact/page.tsx:372',
      detail='"Operations currently active across Lagos and Abuja, with expansion to Port Harcourt and Kano underway." APPS_PUBLISHED is false, the store listings are pending, and the partner directory returns zero stores. Nothing is active anywhere. Not tracked in LAUNCH_CHECKLIST.',
      fix='Remove, or gate on APPS_PUBLISHED and add a checklist entry for the real city list.'),
 dict(id='W-11', sev='HIGH', status='closed', cat='Navigation',
      title='The Terms of Service contents was off by one from section 8',
      loc='terms-of-service/page.tsx:49-66',
      detail='16 TOC entries against 17 rendered sections: section 8, Undeliverable Packages, Storage and Disposal, was added on 2026-08-15 and never added to the TOC. Every entry from 8 to 16 landed on the wrong section and section 17 had no entry at all.',
      fix='Inserted the missing entry; all 17 now align.'),
 dict(id='W-12', sev='HIGH', status='open', cat='False claims',
      title='"Trusted by" displays the SEIRS logo four times as its own social proof',
      loc='src/app/page.tsx:178-181, PartnerMarquee.tsx:46,72-76',
      detail='With no partners signed, the fallback repeats the SEIRS logo four times under a heading reading "Trusted by", with each logo name rendered beside it. The comment argues the stand-in avoids implying a partnership that does not exist, but the heading is itself the implication. Not tracked in LAUNCH_CHECKLIST.',
      fix='Return null when there are no partner logos, and add a checklist entry.'),
 dict(id='W-13', sev='HIGH', status='open', cat='Legal',
      title='privacy@seirs.co is the statutory rights channel and is untracked',
      loc='privacy-policy/page.tsx:117,254,305,333,257',
      detail='All NDPA data-subject requests route there with a binding promise to respond within 30 days. That address is not in launch.ts CONTACT, which lists only support, business, legal and careers. If the mailbox does not exist, statutory access and deletion requests bounce silently.',
      fix='Verify the mailbox and add it to CONTACT as LIVE, or switch the policy to legal@seirs.co.'),
 dict(id='W-14', sev='HIGH', status='closed', cat='Broken links',
      title='The public API hands business partners a 404 tracking URL',
      loc='seirs-backend/src/developer-platform/v1.service.ts:174,269,298',
      detail='Returned https://seirs.app/t/<code> from create-delivery, the sandbox and the test endpoint. The site serves /track/[code]; there is no /t/. Every business integrating over REST receives a dead URL and embeds it in THEIR OWN order-confirmation emails to THEIR customers. It is the one broken link that propagates outside SEIRS entirely, and a partner hits it during sandbox testing before they ever go live.',
      fix='Now builds from PUBLIC_SITE_URL with the /track/ path, matching the rest of the backend.'),
 dict(id='W-M1', sev='MEDIUM', status='open', cat='Tracking page',
      title='A bad code and a network error are indistinguishable',
      loc='track/[code]/page.tsx:132-147,169',
      detail='One catch covers both the not-ok throw and a fetch rejection, and the render shows "Tracking not found" either way. An offline user is told their code is wrong.',
      fix='Catch TypeError separately and offer a retry.'),
 dict(id='W-M2', sev='MEDIUM', status='open', cat='Tracking page',
      title='awaitingPayment is ignored, so the page invents progress',
      loc='track/[code]/page.tsx:42-72',
      detail='The backend returns awaitingPayment with a comment saying the tracking page uses it to say "waiting for payment" instead of inventing progress. The interface does not declare it and nothing renders it, so an unpaid booking shows pending and reads "Awaiting driver": exactly what the field was added to prevent.',
      fix='Declare and render it, matching the app amber/brand-yellow unpaid state.'),
 dict(id='W-M3', sev='MEDIUM', status='open', cat='Tracking page',
      title='kind is ignored, so a tracked ride renders with package language',
      loc='track/[code]/page.tsx', detail='The backend returns kind package|ride; the page shows a Package icon and "Picked up / Drop-off" for a human passenger.', fix='Branch the copy and icon on kind.'),
 dict(id='W-M4', sev='MEDIUM', status='open', cat='Tracking page',
      title='A receiver owing a redirect fee hits a dead end',
      loc='track/[code]/page.tsx vs deliveries.service.ts:1458-1470',
      detail='When the fee is locked the backend returns the dropoff as the literal sentence "SEIRS Partner Store (settle the redirect fee to reveal the pickup location)" plus the amount owed. The tracking page renders that sentence under Drop-off and never links to /collect/<code>, the page built for exactly this.',
      fix='Link to /collect/{code} when redirectFeeOwedNgn > 0.'),
 dict(id='W-M5', sev='MEDIUM', status='closed', cat='Copy',
      title='Reset-password stated the wrong expiry, contradicting the email that sent the user there',
      loc='reset-password/page.tsx:202',
      detail='The page said 30 minutes. The backend sets 15, and email-templates.service.ts:36 tells the user 15. Two surfaces in one flow contradicted each other, and the wrong one was the page the user is looking at when the clock matters.',
      fix='Corrected to 15 minutes.'),
 dict(id='W-M6', sev='MEDIUM', status='open', cat='Cookie banner',
      title='The cookie banner describes cookies that do not exist',
      loc='CookieBanner.tsx:44,8-10, privacy-policy/page.tsx:265-266',
      detail='Says "We use essential cookies to make this site work and optional cookies for analytics" while its own comment says only a localStorage flag is persisted and there are no third-party trackers. The privacy policy separately says no tracking or advertising cookies, and never mentions the website at all.',
      fix='Describe what actually happens.'),
 dict(id='W-M7', sev='MEDIUM', status='open', cat='Cookie banner',
      title='"Accept all" and "Essential only" do the same thing',
      loc='CookieBanner.tsx:25', detail='Both call decide(), which only writes localStorage. Nothing is gated on the value. Two buttons, one outcome.', fix='Gate something, or offer one dismissal.'),
 dict(id='W-M8', sev='MEDIUM', status='open', cat='Cookie banner',
      title='"You can change your mind anytime in the Privacy Policy" is false',
      loc='CookieBanner.tsx:32', detail='The privacy page has no consent control and the banner never reappears once answered. There is no way to change your mind at all.', fix='Add a control or remove the sentence.'),
 dict(id='W-M9', sev='MEDIUM', status='open', cat='Configuration',
      title='The canonical host disagrees three ways and the env var only fixes one',
      loc='layout.tsx:26, sitemap.ts:9, launch.ts:78, CookieBanner.tsx:42',
      detail='layout hardcodes the vercel URL for OpenGraph; sitemap and launch default to seirs.app; the cookie banner hardcodes the string "Cookies on seirs.app". Setting the env var touches none of the hardcoded ones.',
      fix='Import SITE_URL in both hardcoded places. See W-4.'),
 dict(id='W-M10', sev='MEDIUM', status='open', cat='SEO',
      title='No metadataBase, no OG image, no robots.txt',
      loc='layout.tsx, src/app/',
      detail='openGraph is set with no images and no metadataBase, so every share renders as bare text. There is no robots.ts or public/robots.txt, so the sitemap is never announced.',
      fix='Add all three.'),
 dict(id='W-M11', sev='MEDIUM', status='open', cat='Copy',
      title='Brand casing is split across the site',
      loc='layout.tsx:10,27,28,35; Footer.tsx:135; page.tsx:392,468; all four for-* pages; both legal pages; track/[code]:203,354',
      detail='SEIRS in faq, news, careers, changelog, article footers, reset-password and collect; "Seirs" everywhere else. The two tracking pages ("Seirs Tracking", "Powered by Seirs Logistics") are the highest-traffic public surface.',
      fix='SEIRS everywhere.'),
 dict(id='W-M12', sev='MEDIUM', status='open', cat='SEO',
      title='Title template doubles up',
      loc='faq/page.tsx:8, news/page.tsx:9, careers/page.tsx:8, changelog/page.tsx:8 and both dynamic routes',
      detail='Pages set "FAQ - SEIRS" which the layout template renders as "FAQ - SEIRS | Seirs Logistics".', fix='Drop the suffix and let the template supply it.'),
 dict(id='W-M13', sev='MEDIUM', status='open', cat='SEO',
      title='Both tracking pages have no metadata',
      loc='track/page.tsx, track/[code]/page.tsx',
      detail="Both are 'use client' so neither can export metadata; both inherit the generic default title. Tracking is the highest-intent search term a logistics site gets.",
      fix='Wrap each in a server page that exports metadata.'),
 dict(id='W-M14', sev='MEDIUM', status='open', cat='Build',
      title='Type and lint errors are suppressed in production builds',
      loc='next.config.ts:16-21',
      detail='eslint.ignoreDuringBuilds and typescript.ignoreBuildErrors are both true. This defeats the local-build-before-push rule for this app and is why the dead LangSwitcher and unused imports never surfaced.',
      fix='Turn both off and fix what falls out.'),
 dict(id='W-M15', sev='MEDIUM', status='open', cat='Security',
      title='renderMarkdown is injectable',
      loc='src/lib/cms.ts:146,184',
      detail='esc escapes only & < >, not quotes, and inline() builds an anchor href with no protocol allowlist. A CMS body containing a javascript: link or a quote-breaking href renders live via dangerouslySetInnerHTML on /faq, /changelog, /news/[slug] and /careers/[slug]. Admin-authored content only, so admin-to-visitor stored XSS rather than open, but the guard is one line.',
      fix='Escape quotes and reject any href not starting http://, https://, / or mailto:.'),
 dict(id='W-M16', sev='MEDIUM', status='open', cat='Admin-tunable',
      title='Vehicle capacities are hardcoded against a versioned, admin-tunable card',
      loc='for-drivers/page.tsx:233-253',
      detail='States 5 / 20 / 100 / 200 / 800 kg. Currently CORRECT against the seeded card, but the card is versioned and admin-editable and the apps already merge the live card over bundled defaults. These become false the first time an admin edits the card, silently.',
      fix='Fetch from the live card.'),
 dict(id='W-M17', sev='MEDIUM', status='open', cat='Admin-tunable',
      title='Two naira amounts remain hardcoded in the Terms',
      loc='terms-of-service/page.tsx:213,240',
      detail='"loyalty points (N10 per point)" and "Maximum liability N50,000 per package", after N500 per package was removed for exactly this reason. Both live in the Fee Catalogue, and the existing legal audit separately flags the N50,000 cap as unsupported.',
      fix='Render from config or remove the figures.'),
 dict(id='W-M18', sev='MEDIUM', status='open', cat='Legal',
      title='Both legal pages are dated 30 April but were materially changed in August',
      loc='privacy-policy/page.tsx:57, terms-of-service/page.tsx:85,415-416',
      detail='Terms section 8 carries a 2026-08-15 comment, and section 16 promises at least 14 days notice before material changes. The stale date makes that promise unverifiable and is itself inaccurate.',
      fix='Update both dates whenever the text changes.'),
 dict(id='W-M19', sev='MEDIUM', status='open', cat='Legal',
      title='Privacy section 9 does not cover the public website',
      loc='privacy-policy/page.tsx:265-266',
      detail='Addresses only mobile apps and the admin dashboard, while the site sets two localStorage keys and shows a consent banner. Under NDPA the notice should describe the surface the visitor is standing on.',
      fix='Add a website section.'),
 dict(id='W-M20', sev='MEDIUM', status='open', cat='Broken links',
      title='The homepage hardcodes 11 CMS slugs that 404 if unpublished',
      loc='page.tsx:338,543-552, news/[slug]/page.tsx:115',
      detail='Links one news slug and ten moving-* slugs; the article route calls notFound() when the CMS has no match. Any unpublished slug is a 404 reachable from the homepage.',
      fix='Fetch the article list server-side and only render tiles whose slug resolves.'),
 dict(id='W-M21', sev='MEDIUM', status='open', cat='Copy',
      title='Two pages disagree on partner payouts',
      loc='for-business/page.tsx:229, for-partner-stores/page.tsx:174, terms section 3.4',
      detail='"Weekly automatic payout to your bank" vs "Payout details are agreed at onboarding" vs "Weekly payouts are processed every Monday".', fix='Pick one.'),
 dict(id='W-M22', sev='MEDIUM', status='open', cat='Copy',
      title='Contact support status is hardcoded "Currently Online"',
      loc='contact/page.tsx:428-431,439,433-434',
      detail='A pulsing green dot and "Currently Online" render unconditionally, directly above stated hours of Monday to Friday 8am to 6pm. It says online at 3am on a Sunday. It also commits to a 2-hour response for business account holders, of whom there are none.',
      fix='Compute from the hours.'),
 dict(id='W-M23', sev='MEDIUM', status='closed', cat='Configuration',
      title='Every transactional email footer was pinned to the vercel host',
      loc='seirs-backend/src/mail/mail.service.ts:13,58,60,62,352,386',
      detail='The logo image and the Help centre, Contact support and Privacy links were hardcoded, bypassing the WEBSITE_URL the same file already used for reset links. If seirs.app becomes canonical and that deployment is renamed, every SEIRS email renders with a broken logo and four dead links, retroactively, including emails already sitting in inboxes.',
      fix='All six now read from a module-level WEB constant backed by WEBSITE_URL.'),
 dict(id='W-M24', sev='MEDIUM', status='open', cat='Assets',
      title='The contact page ships a placeholder image outside the admin slot system',
      loc='contact/page.tsx:352-357,347-350',
      detail='Hardcodes /placeholders/contact-lagos.jpg. The file exists so it is not broken, but the comment admits the img_contact_lagos slot is not wired here, and HeroBackdrop already solves this. Not in LAUNCH_CHECKLIST.',
      fix='Wire the slot and add a checklist entry.'),
 dict(id='W-M25', sev='MEDIUM', status='open', cat='Links',
      title='External store URLs go through next/link without target or rel',
      loc='how-it-works/page.tsx:138,140,313; for-drivers/page.tsx:122,416',
      detail='PageHero and PageCta render a Link, while GetAppButton and AppStoreBadges use target blank with rel noopener for the same destinations. Inconsistent, and these navigate away from the site.',
      fix='Match the badge behaviour.'),
 dict(id='W-L1', sev='LOW', status='open', cat='Dead code',
      title='LangSwitcher is 72 lines of dead code',
      loc='Nav.tsx:149-220,92', detail='Defined and never rendered; its only reference is inside a comment. LANGS, LANG_STORAGE_KEY and two icon imports are dead with it.', fix='Delete.'),
 dict(id='W-L2', sev='LOW', status='open', cat='Comments',
      title='Five stale comments',
      loc='news/[slug]:9, careers/[slug]:8, SentryInit.tsx:5, Footer.tsx:122-124, page.tsx:840-845',
      detail='Two claim a Next.js export mode the config explicitly documents removing; one calls this the static-export marketing site; one says the store badges render in a coming-soon state that was removed on 2026-08-14; one says "the four below" over a three-item array.',
      fix='Rewrite.'),
 dict(id='W-L3', sev='LOW', status='open', cat='Docs',
      title='LEGAL_AUDIT_REPORT.md is stale and violates the em-dash rule',
      loc='apps/seirs-website/LEGAL_AUDIT_REPORT.md',
      detail='States twice that section 6 names Paystack; the current Terms name Flutterwave. It also contains 65 em-dashes, the only em-dashes anywhere in the app.',
      fix='Refresh it or move it out of the app root.'),
 dict(id='W-L4', sev='LOW', status='open', cat='Accessibility',
      title='Two computed colour-contrast failures',
      loc='page.tsx:150 and all for-* FeatureCard bodies; Footer.tsx:134,140,147,154',
      detail='text-muted #6B7280 on off-white #F5F5F0 is 4.42:1, under the 4.5:1 AA threshold, and is used for body copy site-wide. text-white/40 on navy is 3.52:1 at text-xs, used for the footer Privacy Policy, Terms of Service and Careers links: the worst place for it.',
      fix='Darken the muted token and use text-white/55 in the footer.'),
 dict(id='W-L5', sev='LOW', status='open', cat='Polish',
      title='not-found.tsx renders a plain letter instead of the logo',
      loc='not-found.tsx:8', detail='A bare "S" in a square rather than the SeirsLogo component every other page uses, and it exports no metadata.', fix='Use the component.'),
 dict(id='W-L6', sev='LOW', status='open', cat='Correctness',
      title='The collect page does not encode the code in its fetch URL',
      loc='collect/[code]/page.tsx:61', detail='Unlike track/[code], which does.', fix='encodeURIComponent.'),
 dict(id='W-L7', sev='LOW', status='open', cat='Money',
      title='The collect page can render fractional naira',
      loc='collect/[code]/page.tsx:42', detail='toLocaleString with no options, so a decimal fee renders as N1,500.5.', fix='maximumFractionDigits 0.'),
 dict(id='W-L8', sev='LOW', status='open', cat='Wrong data',
      title='Career location always falls back to "Lagos, Nigeria"',
      loc='careers/page.tsx:65, careers/[slug]/page.tsx:53',
      detail='Reads (r as any).meta?.location, but meta is not a field on WebsiteContent, so it is always undefined. Silently non-functional.', fix='Add the field or drop the lookup.'),
 dict(id='W-L9', sev='LOW', status='open', cat='Polish',
      title='A Phone icon on a mailto link',
      loc='contact/page.tsx:57-60', detail='The "Delivery Issues" card uses a Phone icon for a mailto link showing an email address.', fix='Use a Mail icon.'),
 dict(id='W-L10', sev='LOW', status='open', cat='Dead code',
      title='A dead interface field contradicted by its own comment',
      loc='track/[code]/page.tsx:54,339-343', detail='proofPhotoUrl is declared but the backend deliberately omits it and nothing renders it.', fix='Remove.'),
 dict(id='W-L11', sev='LOW', status='open', cat='Accessibility',
      title='The cookie banner breaks heading order and mislabels its dismiss',
      loc='CookieBanner.tsx:47-53', detail='Places an h2 inside a fixed overlay on every page, and labels the X "Dismiss" while it persists a permanent declined.', fix='Use a div and relabel.'),
 dict(id='W-L12', sev='LOW', status='open', cat='Repo hygiene',
      title='A stale out/ directory in the app root',
      loc='apps/seirs-website/out/', detail='A static export left from the removed output mode. Untracked, so harmless, but it contains only 6 of the 21 routes and there is no local .gitignore.', fix='Delete and gitignore.'),
 dict(id='W-L13', sev='LOW', status='open', cat='Copy',
      title='Two soft time claims on pages that otherwise avoid them',
      loc='page.tsx:428, how-it-works/page.tsx:281 vs for-drivers/page.tsx:342-345',
      detail='"dispatched to your pickup in minutes", and "Onboarding takes about ten minutes" sitting oddly beside "Approval usually takes one to three business days".',
      fix='Soften or remove.'),
 # ── cross-cutting platform items ─────────────────────────────────────────
 dict(id='P-1', sev='MEDIUM', status='closed', cat='Shared components', device=True,
      title='The theme switch read "Light Mode: ON" while the app was plainly dark',
      loc='shared/components/Drawer.tsx:185,188',
      detail='The label named the DESTINATION (tap to go light) while the switch value named the STATE (dark is on), so they contradicted each other in both directions. Shared, so all three apps had it.',
      fix='The row is now always labelled Dark Mode: on means dark, off means light, true in both states. Verified on device in both themes.'),
 dict(id='P-2', sev='HIGH', status='open', cat='Pricing engine',
      title='highValue is null on the rate card, so the premium is not admin-tunable',
      loc='rate card v2, pricing.service.ts:947-953',
      detail='The high-value premium (N500 on a N150,000 declared value, verified live) comes from a CODE FALLBACK of thresholdNgn 50,000 and premiumPct 0.5, because the card has no highValue object at all. The founder cannot change the threshold or the percentage from the dashboard, which breaks the admin-tunable-everything rule on a real money line.',
      fix='Seed highValue onto the card via the self-heal pattern so the dashboard can edit it, keeping the code values as the fallback.'),
 dict(id='P-3', sev='MEDIUM', status='open', cat='Pricing engine',
      title='regions is empty, so no city multiplier applies anywhere',
      loc='rate card v2 regions[]',
      detail='Lagos is priced identically to everywhere else. The engine supports a regional multiplier and hotspot circles; the card carries none.',
      fix='FOUNDER INPUT NEEDED on the actual multipliers, then seed them.'),
 dict(id='P-4', sev='MEDIUM', status='open', cat='Pricing engine',
      title='serviceFees are both 0, so the service fee is not live',
      loc='rate card v2 serviceFees { rideNgn: 0, packageNgn: 0 }',
      detail='The fee the founder meant to publish is not being charged on either product. Note this is what exposed C-D2: the client bundled card computes an 18% percentage service fee while the server charges a flat 0.',
      fix='FOUNDER INPUT NEEDED on the amount, then publish through the dashboard.'),
]
