/**
 * Turn OFF Android's navigation-bar contrast scrim.
 *
 * THE BUG THIS FIXES. With edge-to-edge on, the navigation bar is
 * transparent and shows whatever the app draws behind it, which is how
 * "the bar follows the theme" is supposed to work. But Android also has
 * `enforceNavigationBarContrast`, on by default, which paints a pale
 * scrim behind the bar so the buttons stay visible. Expo's generated
 * theme sets it to true, so on every dark screen in all three apps the
 * bottom of the display was a light strip with dark buttons, no matter
 * what the JavaScript asked for. The founder hit it twice: once on the
 * business partner drawer and once on the customer drawer
 * (2026-09-04 and 2026-09-05).
 *
 * It also silently disabled the fix: expo-navigation-bar's `setStyle()`
 * is documented to take effect only when this flag is false, and the
 * older `setButtonStyleAsync()` is not supported under edge-to-edge at
 * all. Our call was wrapped in `.catch(() => {})`, so when it refused,
 * nothing was logged and the bar looked broken for no visible reason.
 *
 * WHY A PLUGIN. android/ is gitignored in all three apps, so styles.xml
 * is regenerated by prebuild every time and cannot be edited by hand.
 *
 * This changes the APK, so it needs a native rebuild to take effect.
 */
const { withAndroidStyles } = require('@expo/config-plugins');

const ITEM = 'android:enforceNavigationBarContrast';

module.exports = function withNavBarContrast(config) {
  return withAndroidStyles(config, (cfg) => {
    const styles = cfg.modResults;
    const app = (styles.resources.style ?? []).find((s) => s.$?.name === 'AppTheme');
    if (!app) return cfg;

    app.item = app.item ?? [];
    const existing = app.item.find((i) => i.$?.name === ITEM);
    if (existing) {
      existing._ = 'false';
    } else {
      app.item.push({ _: 'false', $: { name: ITEM, 'tools:targetApi': '29' } });
    }
    return cfg;
  });
};
