export {
  configureApi,
  onSessionExpired,
  setSessionExpiredHandler,
  uploadApi,
  authApi,
  usersApi,
  deliveriesApi,
  paymentsApi,
  driversApi,
  notificationsApi,
  dropoffApi,
  identityApi,
  userVerificationApi,
  chatApi,
  documentsApi,
  sosApi,
  offlineSyncApi,
  feesApi,
  mapsApi,
  storiesApi,
  partnerApi,
  configApi,
  pricingApi,
  loyaltyApi,
  promotionsApi,
  suggestionsApi,
  // Wave 16B additions
  addressesApi,
  supportApi,
  // Wave 16E addition
  maintenanceApi,
  // Raw request helper. The SOS screen reads GET /config/emergency-contacts,
  // an admin-managed list that has no typed wrapper in shared yet. Exported
  // here so the screen does not hand-roll a fetch and lose the auth header
  // and the 401 session handling.
  request as apiRequest,
} from '@seirs/shared/services/api';

export type {
  StoryDTO,
  FeaturedCardDTO,
  ChatMessageDTO,
  ChatConversationDTO,
  UserDocumentDTO,
  ServiceCategory,
  RateCard,
  PriceBreakdown,
  QuoteInput,
  SavedCard,
  LoyaltyEntry,
  ReferralHistoryItem,
  LoyaltyTier,
  PromoDTO,
  FlutterwavePaymentOption,
  SavedAddressDTO,
  IdentityDocType,
  // Chat 5 support toolkit
  SupportTicketDTO,
  SupportThreadDTO,
  TicketTopic,
  TicketStatus,
} from '@seirs/shared/services/api';
