export {
  configureApi,
  onSessionExpired,
  setSessionExpiredHandler,
  uploadApi,
  authApi,
  usersApi,
  deliveriesApi,
  paymentsApi,
  driversApi,
  notificationsApi,
  dropoffApi,
  identityApi,
  userVerificationApi,
  chatApi,
  sosApi,
  offlineSyncApi,
  feesApi,
  storiesApi,
  partnerApi,
  configApi,
  pricingApi,
  loyaltyApi,
  promotionsApi,
  suggestionsApi,
  // Wave 16B additions
  addressesApi,
  ticketsApi,
  supportApi,
  // Wave 16E addition
  maintenanceApi,
} from '@seirs/shared/services/api';

export type {
  StoryDTO,
  ChatMessageDTO,
  ChatConversationDTO,
  ServiceCategory,
  RateCard,
  PriceBreakdown,
  QuoteInput,
  SavedCard,
  LoyaltyEntry,
  ReferralHistoryItem,
  LoyaltyTier,
  PromoDTO,
  FlutterwavePaymentOption,
  SavedAddressDTO,
  IdentityDocType,
  // Chat 5 support toolkit
  SupportTicketDTO,
  SupportThreadDTO,
  TicketTopic,
  TicketStatus,
} from '@seirs/shared/services/api';
