export {
  configureApi,
  onSessionExpired,
  setSessionExpiredHandler,
  uploadApi,
  authApi,
  usersApi,
  deliveriesApi,
  paymentsApi,
  driversApi,
  notificationsApi,
  dropoffApi,
  identityApi,
  chatApi,
  sosApi,
  offlineSyncApi,
  feesApi,
  partnerApi,
  configApi,
  pricingApi,
  loyaltyApi,
} from '@seirs/shared/services/api';

export type {
  ChatMessageDTO,
  ChatConversationDTO,
  ServiceCategory,
  RateCard,
  PriceBreakdown,
  QuoteInput,
  SavedCard,
  LoyaltyEntry,
  LoyaltyTier,
} from '@seirs/shared/services/api';
